### ISSUE TITLE
Fish autocompletion doesn't seem to work

### ISSUE THREAD

**Issue by Norlock** [void-linux/xbps#10]
* xuname:
Void 4.17.9_1 x86_64 GenuineIntel uptodate rF
* package:
fish-shell

## Expected behavior
sudo xbps-install -S ra -> tab -> show packages starting with ra

## Actual behavior
shows files or directories starting with ra

**Comment by Norlock** [comment]
A sidenote I can't register to the official forum, since I don't receive a confirmation email.

**Comment by maxice8** [comment]
run `fish_update_completion` which parses manpages and generates completion.

![image](https://user-images.githubusercontent.com/30738253/50476338-f58b0900-09ae-11e9-9c3c-83bd0b82aa97.png)
