### ISSUE TITLE
[Feature request] add a preserv-config option to xbps.d file preservation lists

### ISSUE THREAD

**Issue by mrshampoo** [void-linux/xbps#100]
It would sometimes be nice to preserve some config files, but still get the updated config to look at.
like a "name-of-config.newversion" copied in to the same dir as the file you want to preserve.

**Comment by Anachron** [comment]
That‘s default, isn‘t it?

As soon as the shipped version changes it will create the file with a version suffix in the target folder. It will not automatically override it.

**Comment by mrshampoo** [comment]
I have never noticed any "*.version" files... is my system buggy or something then perhaps?
cause my /etc/bash/bashrc get over written quit often. or do you meen if I have already set it on preserve?
(It didn't  overwrite bashrc this update, that i made yesterday, but I thought that i might as well bring that file up while I'm still at it (I asked in the redit forum for just preservation in regular, and then Duncan mentioned this to config files and suggested me to start an "issue") )

**Comment by Duncaen** [comment]
This already exists and I meant to open an issue to get the file marked as configuration file in the void-packages repository.
