### ISSUE TITLE
xbps-remove: marks package as removed, ignoring errors

### ISSUE THREAD

**Issue by innerspacepilot** [void-linux/xbps#110]
Hello!
I have root mounted ro.
When I remove a package i get:
`# xbps-remove makeself

Name     Action    Version           New version            Download size
makeself remove    2.4.0_3           -                      - 

Size freed on disk:             37KB
Space available on disk:      1301MB

Do you want to continue? [Y/n] 
Removing `makeself-2.4.0_3' ...
ERROR: makeself-2.4.0_3: failed to remove file `/usr/bin/makeself': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove file `/usr/bin/makeself-header': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove file `/usr/share/man/man1/makeself.1': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove directory `/usr': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove directory `/usr/bin': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove directory `/usr/share': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove directory `/usr/share/man': Read-only file system
ERROR: makeself-2.4.0_3: failed to remove directory `/usr/share/man/man1': Read-only file system
Removed `makeself-2.4.0_3' successfully.

0 downloaded, 0 installed, 0 updated, 0 configured, 1 removed.
#`
I think there should be an error reported and package left as installed or partially installed, so I could continue removing it after remounting root as rw.

Thank you.

**Comment by xtraeme** [comment]
I see.

**Comment by xtraeme** [comment]
It's just the informative messages that are wrong. As your rootfs is read-only, xbps couldn't write to the pkgdb...

**Comment by xtraeme** [comment]
Hmm, well I can't reproduce it...

```
[juan@leysa xbps]$ xbps-remove -r /mnt/target -v makeself
failed to lock pkgdb: Read-only file system
```

`/mnt/target` is f2fs mounted read-only. Not sure how you made it able to lock the pkgdb if the fs is read-only.

**Comment by xtraeme** [comment]
If you can give me precise instructions in how to reproduce your issue I'll fix it... otherwise I cannot reproduce it with xbps from git.

**Comment by innerspacepilot** [comment]
Ooops :)
/var is mounted rw

**Comment by xtraeme** [comment]
Ah, heh.

**Comment by xtraeme** [comment]
Ok, fixed:

```
[juan@leysa xbps]$ sudo chroot target/target /bin/sh
[\u@\h \W]$ /var/xbps-remove.static -yvd makeself
[DEBUG] XBPS: 0.54 API: 20180730 GIT: c3b2d7ca
[DEBUG] Processing configuration directory: /usr/local/etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/local/share/xbps.d
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/usr/local/etc/xbps.d
[DEBUG] sysconfdir=/usr/local/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
[DEBUG] [pkgdb] initialized ok.
[DEBUG] [pkgdb] rootdir /: Read-only file system
failed to lock pkgdb: Read-only file system
[\u@\h \W]$ 
[juan@leysa xbps]$ mount|grep target
/dev/sdb1 on /home/juan/projects/void-linux/xbps/target type f2fs (ro,relatime,lazytime,background_gc=off,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,extent_cache,mode=adaptive,active_logs=6,alloc_mode=reuse,fsync_mode=posix)
/dev/sdb2 on /home/juan/projects/void-linux/xbps/target/target/var type f2fs (rw,relatime,lazytime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=reuse,fsync_mode=posix)
[juan@leysa xbps]$
```

**Comment by huglovefan** [comment]
reproduction case 2: try removing a kernel package with `/boot` read-only

i think you'll get the same bug but the fix in https://github.com/void-linux/xbps/pull/111 isn't enough to catch it

**Comment by xtraeme** [comment]
@huglovefan right. It's a known bug.

I think we could check for the top level dirs in rootdir to avoid this.

**Comment by xtraeme** [comment]
But for this specific case #111 fixes it.

**Comment by xtraeme** [comment]
We can file another issue explaining the `/boot` case.
