### ISSUE TITLE
Compatibility with xbps<0.54 repodata

### ISSUE THREAD

**Issue by xtraeme** [void-linux/xbps#122]
xbps-0.54 has switched the default repodata compression format to zstd.

That means that once the builder builds it, next job in buildbot will generate a zstd compressed repodata, making all xbps users unable to update.

To fix this scenario, the repodata files must be renamed and if the new repodata file does not exist, fallback to the previous format, i.e `<arch>-repodata`.

I vote for `<arch>-repodata.xbps`

What do you think about this? (hi @Gottox and @Duncaen)

**Comment by pullmoll** [comment]
Wouldn't it be easier to have the `<arch>-repodata` files gzip compressed as it is now and use zstd only for the `*.xbps` files? Also with the `<arch>-repodata.xbps` suffix filters relying on `*.xbps` being package files may fail.

**Comment by xtraeme** [comment]
@pullmoll the extension does not matter at all. They are tar archives with compression.

I'd switch both repodata and binpkgs, but I thought maybe people prefer xz to its high compression ratio.

**Comment by xtraeme** [comment]
@pullmoll you've got a point. In that case just `<arch>.repodata`

**Comment by xtraeme** [comment]
0.53: `<arch>-repodata`
0.54 proposed: `<arch>.repodata`

**Comment by pullmoll** [comment]
The `*-repodata` files are 1-2 MiB in size IIRC so you could save let's say 16 MiB of space in the entire repository. Of course downloads would be a tad quicker while usually the packages to download are way larger than the metadata.

Also you can inspect current `<arch>-repodata` with almost any `tar` because even old systems support gzipped tarballs in one way or another while zstd needs additional, external tools or a modern tar. Just my .02 of thoughts.

**Comment by pullmoll** [comment]
This is before and after recompressing the current x86_64-repodata with `zstd -9`.
```
1.888.653 x86_64-repodata
1.582.363 x86_64.repodata
```
That is < 20% saving.

**Comment by pullmoll** [comment]
This is before and after recompressing the current x86_64-repodata with `zstd -9`.
```
1.888.653 x86_64-repodata
1.582.363 x86_64.repodata
```
That is < 20% saving.

**Comment by xtraeme** [comment]
I've used lvel 19 because this is what Debian choosed. I've read that higher than that makes decompression slower, the manpage said so.

**Comment by xtraeme** [comment]
With xbps from git you can use:
```
$ xbps-create - - compression xz|lz4|zstd...
$ xbps-rindex - - compression...
```

**Comment by Gottox** [comment]
xbps-rindex (or xbps-src) needs a compatibility mode where it generates both files for a grace time. also the cleanup scripts need to be compatible with the change.

**Comment by Vaelatern** [comment]
I'd vote for the minimum version number needed to parse repodata being in the name.

**Comment by xtraeme** [comment]
This is consistent with pkgdb too. `<arch>-repodata-0.54`

Good suggestion!

**Comment by Vaelatern** [comment]
So now all xbps would need for falling back would be a list of such version numbers.

**Comment by xtraeme** [comment]
I'd like to see votes for default compression in repodata and binpkgs.

Currently:
- binpkgs -> xz
- repodata -> zlib

My vote:
- binpkgs -> zstd
- repodata -> ztd

Please vote to have a final decission!

**Comment by xtraeme** [comment]
I'll add code to handle new and old repodata archives for full compatibility.

**Comment by Vaelatern** [comment]
What are the benefits of switching, other than standardizing on one mechanism?

**Comment by xtraeme** [comment]
lz4 and zstd are way faster than lzma at decompression, this would make `xbps-query -R` even a bit faster, or any other operation with repos.

Personally I really think lzma is great for compression ratio but it takes too much memory and decompression time is much slower than lz4/zstd.

But if people prefer to keep as is currently I don't mind.

**Comment by jnbr** [comment]
Switching the `repodata` from `zlib` to `zstd` gives a speedup of 3.6% ( 9 ms ) on my laptop for `xbps-query -R`.

The bigger speedup for most users would be to switch the binpkgs to zstd but this can't be done as long as old versions of xbps must be supported (given that we don't want to provide each package in both compression formats).

I think it makes more sense to add decompression support for zstd now and switch both, or binpkgs only, after a grace period.

**Comment by xtraeme** [comment]
I came to the conclusion that it's better to keep what we use, and then if somebody wanna change the defaults just tweak them via cmdline options.

So I'll revert master to what we use currently to not break any compatibility.

This also means that anybody with xbps-0.54 will be able to use any compression format used by repodata/binpkgs on the fly.
