### ISSUE TITLE
Useless / not informative error messages

### ISSUE THREAD

**Issue by innerspacepilot** [void-linux/xbps#123]
Hello,
root is mounted ro,
/var is mounted rw
error messages should say something about read-only fs

`# xbps-install dbus

Name Action    Version           New version            Download size
dbus install   -                 1.12.16_1              111KB 

Size to download:              112KB
Size required on disk:         526KB
Space available on disk:      1283MB

Do you want to continue? [Y/n] 

[*] Downloading binary packages
dbus-1.12.16_1.armv7l-musl.xbps: 111KB [avg rate: 326MB/s]
dbus-1.12.16_1.armv7l-musl.xbps.sig: 512B [avg rate: 4274KB/s]

[*] Verifying package integrity
dbus-1.12.16_1: verifying RSA signature...

[*] Running transaction tasks
dbus-1.12.16_1: unpacking ...
ERROR: dbus-1.12.16_1: [unpack] failed to extract file `./usr/share/xml/dbus-1/introspect.dtd': No such file or directory
ERROR: dbus-1.12.16_1: [unpack] failed to extract files: No such file or directory
ERROR: dbus-1.12.16_1: [unpack] failed to unpack files from archive: No such file or directory
# mount -o remount,rw /
# xbps-install dbus

Name Action    Version           New version            Download size
dbus install   -                 1.12.16_1              - 

Size required on disk:         414KB
Space available on disk:      1283MB

Do you want to continue? [Y/n] 

[*] Downloading binary packages

[*] Verifying package integrity
dbus-1.12.16_1: verifying RSA signature...

[*] Running transaction tasks
dbus-1.12.16_1: unpacking ...

[*] Configuring unpacked packages
dbus-1.12.16_1: configuring ...
Created dbus (gid 22) system group.
Created dbus (22) system user.
dbus-1.12.16_1: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
#`

**Comment by xtraeme** [comment]
Is this with git master? Try xbps-install - V

**Comment by innerspacepilot** [comment]
XBPS: 0.53 API: 20180730 GIT: UNSET

**Comment by xtraeme** [comment]
This has been fixed in master, you are using an old version that does not contain the changes.

```
[juan@leysa xbps]$ xbps-query -V
XBPS: 0.54 API: 20190615 GIT: 9a2a85d2
```

How to install from git without fucking up your system?
(execute all commands as user, not root!)
```
$ git clone https://github.com/void-linux/xbps
$ cd xbps
$ ./configure --enable-rpath --prefix=/usr --sysconfdir=/etc
$ make -j$(nproc)
$ make DESTDIR=~/xbps-git install clean
$ export PATH=~/xbps-git/usr/bin:$PATH
$ xbps-query -V
...
```

**Comment by innerspacepilot** [comment]
by the way,
git master build fails
make[2]: Entering directory '/home/str/xbps/bin/xbps-checkvers'
 [CC]		main.o
main.c: In function 'rcv_sh_substitute':
main.c:230:29: error: comparison is always true due to limited range of data type [-Werror=type-limits]
      while ((c = fgetc(fp)) != EOF && c != '\n') {
                             ^~
cc1: all warnings being treated as errors

had to add -Wno-error,
gcc 8.3.0

tested,
builded binaries report "Failed to lock the pkgdb: Read-only file system"
so, for now, bug can be closed.
How soon these binaries will arrive to system?

Thank you

**Comment by xtraeme** [comment]
what CFLAGS did you use?

**Comment by Duncaen** [comment]
It is arm, with unsigned chars by default. I switched `int c` to `char c` for the `fgetc` function, without thinking.
Changed it back to `int c`, so the checks like `c != EOF` work again.

**Comment by xtraeme** [comment]
Ah ok, fixed then. Thanks!
