### ISSUE TITLE
xbps-install does not respect XBPS_ARCH

### ISSUE THREAD

**Issue by CorporalCrawdad** [void-linux/xbps#13]
In trying to install musl-void to an alternate partition of my computer, I have tried the command
`XBPS_ARCH=x86_64-musl xbps-install -S -R http://repo.voidlinux.eu/current/musl -r /mnt`
and gives the output
`[*] Updating 'http://repo.voidlinux.eu/current/musl/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file 'http://repo.voidlinux.eu/current/musl/x86_64-repodata': Not Found`

Despite setting XBPS_ARCH, xbps-install is stubbornly using my local install's settings. The only relating issue I can find is on the pre-migrated xbps [https://github.com/voidlinux/xbps/issues/69](#69), but this talks about changing settings in xbps.d, which can't be done until a base system has been installed. If this is expected behavior, then the manpage is a little misleading...

**Comment by Duncaen** [comment]
Verbose/debug output? What shell are you using?

**Comment by CorporalCrawdad** [comment]
Adding verbosity does not change the output, but I was using zsh for shell.
I tried switching to bash and it works just fine... I guess I'll bark up the zsh tree. Issue closed.
