### ISSUE TITLE
xbps-install asks for confirmation even if every package is already installed

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/xbps#134]
`xbps-install dash`
 results in
```
Package `dash' already installed.

Name Action    Version           New version            Download size

Space available on disk:      3440MB

Do you want to continue? [Y/n] 
```
but I expected only to get the information that the package is already installed
```Package `dash' already installed.```

**Comment by xtraeme** [comment]
fixed with https://github.com/void-linux/xbps/commit/58509996aabea52ffc40e5e01c9eb00730c6cdcc
