### ISSUE TITLE
Update reports broken/uresolved dependency

### ISSUE THREAD

**Issue by marcdraco** [void-linux/xbps#138]
libuuid-2.34_1 (update) breaks installed pkg `libblkid-32bit-2.33.2_1'
libuuid-2.34_1 (update) breaks installed pkg `libmount-32bit-2.33.2_1'
Transaction aborted due to unresolved dependencies.

**Comment by xtraeme** [comment]
Not a bug, working as expected.

**Comment by xtraeme** [comment]
libuuid cannot be upgraded to 2.34_1 because there are no updates to the other 32bit packages that depend on it.

Solution:
- you need the "multilib" repository
- the "multilib" repository needs to be up-to-date
- xbps-install -Su

**Comment by tha1** [comment]
> libuuid cannot be upgraded to 2.34_1 because there are no updates to the other 32bit packages that depend on it.
> 
> Solution:
> 
>     * you need the "multilib" repository
> 
>     * the "multilib" repository needs to be up-to-date
> 
>     * xbps-install -Su

is there a solution for 32bit installs of void?  i cannot install dwm from source with this broken dependency using the void linux dwm guide.  i can xbps-install-S dwm fine but it doesnt actually work after
.

**Comment by Duncaen** [comment]
@tha1 this is the wrong repository. Open an issue in https://github.com/void-linux/void-packages, if it persists after doing a full update using `xbps-install -Su` and provide the actual error messages and maybe a log with `--verbose` and `--debug` flags.
