### ISSUE TITLE
xbps-install fails to replace file with directory on update

### ISSUE THREAD

**Issue by jnbr** [void-linux/xbps#14]
`xbps-install` fails to replace a file with a directory of the same name when updating packages.
Here is an example to trigger the bug: https://github.com/jnbr/void-packages/commit/545a737bd7ff2f1110bdd83712fe8e9f5681fcfe

This is similar to: https://github.com/voidlinux/xbps/issues/220

As a workaround, the affected package can be removed and installed afterwards.

**Comment by cr6git** [comment]
Interesting, it reminds me of this comment about `mixxx`:
https://github.com/mixxxdj/mixxx/blob/master/README#L23

**Comment by luzpaz** [comment]
any proposed workarounds for this ?

**Comment by jnbr** [comment]
> any proposed workarounds for this ?

yes, #22

**Comment by q66** [comment]
Also affects https://github.com/void-linux/void-packages/pull/6053 not because of the change itself but because of an update of the egg system now causing things formerly installed as files to be directories

**Comment by xtraeme** [comment]
This is a long standing bug in xbps, I knew about it for too many years.

But my final decission was that it's better to inform the admin to prepare the rootdir manually in this case.

This case happens rarely so it can be documented appropiately.

**Comment by xtraeme** [comment]
@Duncaen should be fixed now, isn't it?

**Comment by Duncaen** [comment]
Yes, fixed and merged the test from #22.
