### ISSUE TITLE
xbps-src first package installed after xbps update goes missing

### ISSUE THREAD

**Issue by Duncaen** [void-linux/xbps#142]
If there is a bump to xbps itself, the next package xbps-src tries to install will now be the xbps update instead of the package it tried to install.

https://build.voidlinux.org/builders/x86_64-musl_builder/builds/21447/steps/shell_3/logs/stdio

Maybe we could add an EAGAIN exist status in this case so that xbps-src knows that it has to try to install the package again.

**Comment by xtraeme** [comment]
Right, I was aware of that. As xbps now autoupdates itself on any operation the next pkg is skipped completely.

**Comment by xtraeme** [comment]
I like your EAGAIN suggestion.

**Comment by xtraeme** [comment]
I was also thinking in reexecuting xbps itself without the need of another transaction.

**Comment by Duncaen** [comment]
This sounds good too, but I think I have to think about that more, I feel like there are cases where this wouldn't be good.

**Comment by Duncaen** [comment]
Problem with `EAGAIN` would be that I've seen some cases that try to work around this case by doing `xbps-install -Su && xbps-install -Su`.

As example https://github.com/lxc/distrobuilder/blob/93d5e7614bd12d4c3f1b5eadfce5a9b607d05350/managers/xbps.go#L32.
