### ISSUE TITLE
xbps-install slows down

### ISSUE THREAD

**Issue by ekomizer** [void-linux/xbps#143]
This started happening after the recent several `xbps` updates/revisions.

Whenever I install some package/s or update the system, downloads start at a normal speed (to where my normal connection speed is) then gradually slows down (even reaches down to kbps). Sometimes, it also goes to a point where it outputs transaction failed errors.

I did some inspection and found out that this problem is not present on other things (torrents and/or other downloads, cloning large repos, etc.).

**Comment by xtraeme** [comment]
I'm also experiencing this but I'm not sure if it's related to the happy eyeball changes? @Duncaen

**Comment by Anachron** [comment]
Same things happening here. 

Pretty easy to recognize when you recently upgraded your internet and the speed drops into the 100s of kb/s.

**Comment by xtraeme** [comment]
I think the issue is in the void servers because I'm able to download at max speed via kernel.org (10MB/s).

**Comment by xtraeme** [comment]
You can check this with `xbps-fetch`

**Comment by Anachron** [comment]
Yep, tested this with http://releases.ubuntu.com/18.04.2/ubuntu-18.04.2-desktop-amd64.iso and got a good 10MB/s speed.

**Comment by xtraeme** [comment]
I also thought there was a problem with our fetch code but looks ok.

**Comment by Duncaen** [comment]
Yes I don't think this is related to happy eyeballs, with the keep alive you only connect once and the time to connect should generally be shorter now, if the DNS has multiple addresses and one is faster than the first one.

**Comment by Anachron** [comment]
I'm still experiencing this issue btw. Right now updating my Void install and it went from 8MB/s to around 500-600KB/s. Has someone checked the mirrors already?

**Comment by Duncaen** [comment]
```
$ xbps-fetch https://alpha.de.repo.voidlinux.org/live/20190217/void-live-x86_64-20190217-mate.iso
void-live-x86_64-20190217-mate.iso: 831MB [avg rate: 14MB/s]
```

**Comment by pullmoll** [comment]
Fetching from alpha.de.repo.voidlinux.org I sometimes see rates as low as 16KB/s for e.g. `x86_64-musl-repodata`.

Fetching from my own repo.voidlinux.de I usually see the expected ~10MB/s.

I also ran `sudo tracebox alpha.de.repo.voidlinux.org` and sometimes see a hop which cannot be identified, e.g. `4: *`. From there, with a delay of about 50 to 70 ms, the trace then continues until e.g. `11: a-hel-fi.m.voidlinux.org (95.216.76.97)`. No clue if that tells anything as I'm no networking pro.

**Comment by Duncaen** [comment]
There is also some trouble with networking between a-hel-fi and the musl buildserver, the sync is really slow.
I was thinking if it is related to disabling SACK, but I think the slow down between a-hel-fi and alpha.us started before SACK was disabled.

**Comment by Vaelatern** [comment]
The slow-down was the reason for disabling SACK.

**Comment by xtraeme** [comment]
Almost 24h since gcc-9.1.0 was built in the x86_64-musl builder and the packages aren't available in alpha.de... there's something serious here.

If that continues I'll stop using the void servers and I'll build everything myself.

**Comment by Vaelatern** [comment]
I mean, the system is set up so you can do that, sure.

**Comment by xtraeme** [comment]
@Vaelatern you seem to talk like the main authority in void.

I was away for 1,5 years and now looks like I'm not part of void anymore... while I SPENT YEARS literally to make void what it is right now.

Not sure what's wrong with you, but you should stop this.

**Comment by xtraeme** [comment]
Definitely the issue is in a-hel-fi.m.voidlinux.org.

**Comment by xtraeme** [comment]
I started building my own stuff locally because any mirror or is outdated or it is too slow to be useful.

**Comment by Gottox** [comment]
@xtraeme the issue is not a-hel-fi.

**Comment by xtraeme** [comment]
@Gottox I don't have any details of how the infrastructure is designed. Nobody gave me details.

But synchronization between a-hel-fi and alpha.de seems to be the issue.

**Comment by the-maldridge** [comment]
You have access to the same details the rest of the world does, which is the entire infrastructure layout and control plan in the infrastructure repo.  https://github.com/void-linux/void-infrastructure.

**Comment by xtraeme** [comment]
Ok, as main author of xbps and everything related to void I declare this not a bug in xbps.

It's an issue in the infrastructure, unrelated to the xbps code.

@ekomizer please open a new issue in https://github.com/void-linux/void-infrastructure

**Comment by Gottox** [comment]
> But synchronization between a-hel-fi and alpha.de seems to be the issue.

a-hel-fi.m and alpha.de are the same box.


> I was away for 1,5 years and now looks like I'm not part of void anymore... while I SPENT YEARS literally to make void what it is right now.

And then you left without letting anyone know, without giving anyone access to resources. I asked you **repeatedly** to let me access the github organisation and the eu-domain so we could manage those resources by ourselves. That was needed as you didn't replied to mails for **weeks**. You denied the requests, then disappeared completely and left void to die. The only reason it did not was because other people cared where you didn't and actually we went to a lot of pain to keep void running. The loss of the eu domain would be so easy to avoid if you just let your ego out of the project and gave me the access the project needed.  Then after TWO FUCKING YEARS where I thought you were literally DEAD you returned and demanded access. Still, we were friendly and gave you the access you needed. Now you're blaming other people, that you don't know what happened in those years since you stopped caring. Please calm down and try to rebuild the trust you destroyed.

**Comment by Gottox** [comment]
@ekomizer Thanks for your report. Unfortunately this is something at the hosting site. We opened an issue for the provider and are waiting for reply.

**Comment by ekomizer** [comment]
@xtraeme @Gottox et al. Thank you very much.
