### ISSUE TITLE
Is it possible to specify the backup repositories?

### ISSUE THREAD

**Issue by hhrhhr** [void-linux/xbps#148]
Today, when installing on a notebook, the server http://alpha.de.repo.voidlinux.org was unavailable (...beta... as it turned out later, too), which is why the installer reported a network error (at the stage of configuring the network card). After manual setup of the network, the installation continued, but only in the "local" mode, and, of course, the post-installation update could not end.
I found a working mirror and updated the configuration files, but a question arose. How can I specify backup repositories that would be used when main ones are unavailable?

**Comment by xtraeme** [comment]
```
echo "repository=firstrepo" >> etc/xbps.d/my-repos.conf
echo "repository=backuprepo" >> etc/xbps.d/my-repos.conf
...
```

See [xbps.d(5)](https://man.voidlinux.org/xbps.d)
