### ISSUE TITLE
Please update xbps static

### ISSUE THREAD

**Issue by zayuim** [void-linux/xbps#150]
Hello,

The static builds (at http://alpha.de.repo.voidlinux.org/static/xbps-static-latest.<arch>-musl.tar.xz) for xbps are at version 0.51.

I was wondering if they could be updated because xbps-src demands =>0.55 when using on a foreign distro.

**Comment by xtraeme** [comment]
Please report this to https://github.com/void-linux/void-infrastructure instead

Thanks

**Comment by the-maldridge** [comment]
This is now being tracked in void-linux/void-infrastructure#48, though this was a bug to do with the release of the xbps release, not the infrastructure that hosts the releases.
