### ISSUE TITLE
ERROR: Failed to initialize libxbps: Permission denied

### ISSUE THREAD

**Issue by edn9** [void-linux/xbps#151]
Hello, I dont know if this is the right place but I'm having this trouble with libxbps. How can I solve the permission problem? Before when I used the command `xbps-query -Rs mysql` I was able to search without sudo, now I need to use to be able to search, how can I make it go back to use without sudo?

Thanks for your attention.

**Comment by xtraeme** [comment]
`/var/db/xbps/pkgdb-0.38.plist`

**Comment by xtraeme** [comment]
Check its permissions, we believe the umask issues were totally fixed for 0.54.

**Comment by edn9** [comment]
_ls -lah /var/db/xbps/pkgdb-0.38.plist
-rw-r--r-- 1 root root 1,8M jul  8  2019 /var/db/xbps/pkgdb-0.38.plist_
So, do I need to use chmod u+x in this package? I'm not sure what to do.

**Comment by Duncaen** [comment]
The permission look fine. Can you maybe provide the output of `xbps-query -Rsd mysql` and maybe `strace xbps-query -Rs msyql`.

**Comment by edn9** [comment]
The first command `xbps-query -Rsd mysql` is not working but I tried `xbps-query -Rs mysql --debug` and I get this, I dont know if is the same action you want to see:
```
[DEBUG] XBPS: 0.56 API: 20190621 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] cannot read configuration file /etc/xbps.d/00-repository-main.conf: Permission denied
ERROR: Failed to initialize libxbps: Permission denied
```
And here the strace info, its a lot of stuff.
[straceinfo.txt](https://github.com/void-linux/xbps/files/3369994/straceinfo.txt)

**Comment by Duncaen** [comment]
```
[DEBUG] cannot read configuration file /etc/xbps.d/00-repository-main.conf: Permission denied
```

try: `chmod o+r /etc/xbps.d/00-repository-main.conf`

**Comment by edn9** [comment]
![image](https://i.imgur.com/mu88XKA.png)

D:

**Comment by Duncaen** [comment]
The permissions are still weird, use 644 or something like that.
And provide logs with `-d` or `--debug`.

**Comment by xtraeme** [comment]
@Duncaen anyway there's a real issue here, even if confdir files can't be read it should still fallback to system confdir (share/xbps.d)

**Comment by xtraeme** [comment]
chmod 0 is a good way to disable conf files

**Comment by edn9** [comment]
Oh, sorry about the screenshots @Duncaen . Also I tried `chmod 644` but still not working, so I used the `--debug` and:

```
search mysql --debug
[DEBUG] XBPS: 0.56 API: 20190621 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Parsing configuration file: /etc/xbps.d/00-repository-main.conf
[DEBUG] /etc/xbps.d/00-repository-main.conf: added repository https://mirrors.dotsrc.org/voidlinux/current
[DEBUG] cannot read configuration file /etc/xbps.d/10-repository-multilib-nonfree.conf: Permission denied
ERROR: Failed to initialize libxbps: Permission denied
~ - ls /etc/xbps.d/
00-repository-main.conf              10-repository-nonfree.conf  xbps.conf
10-repository-multilib-nonfree.conf  20-repository-debug.conf
10-repository-multilib.conf          void-virtualpkgs.conf
~ - ls -lah /etc/xbps.d/
total 40K
drwxr-xr-x  3 root root 4,0K jul  5 14:58 .
drwxr-xr-x 55 root root 4,0K jul  9 10:14 ..
drwx------  2 root root 4,0K jul  5 14:50 .backup
-rw-r--r--  1 root root   56 jul  5 14:58 00-repository-main.conf
-rw-------  1 root root   73 jul  5 14:58 10-repository-multilib-nonfree.conf
-rw-------  1 root root   65 jul  5 14:58 10-repository-multilib.conf
-rw-------  1 root root   64 jul  5 14:58 10-repository-nonfree.conf
-rw-------  1 root root   62 jul  5 14:58 20-repository-debug.conf
-rw-------  1 root root  252 jul  5 14:58 void-virtualpkgs.conf
-rw-------  1 root root 3,2K jul  5 14:58 xbps.conf
```
In my .bashrc file I have this command `umask 0077` to everytime I create a new file, the file will only have permission to read and write for my user only, maybe thats the problem?

```
ls -lah /usr/share/xbps.d/
total 40K
drwxr-xr-x   3 root root 4,0K jul  5 13:51 .
drwxr-xr-x 154 root root 4,0K jul  5 16:32 ..
drwx------   2 root root 4,0K jul  5 13:51 .backup
-rw-------   1 root root   65 jul  5 13:51 00-repository-main.conf
-rw-------   1 root root   72 jul  5 16:26 10-repository-multilib-nonfree.conf
-rw-------   1 root root   64 jul  5 16:26 10-repository-multilib.conf
-rw-------   1 root root   63 jul  5 16:26 10-repository-nonfree.conf
-rw-------   1 root root   61 jul  5 16:26 20-repository-debug.conf
-rw-------   1 root root  252 jul  5 16:26 void-virtualpkgs.conf
-rw-------   1 root root 3,2K jul  5 16:26 xbps.conf
```

**Comment by Anachron** [comment]
Yes that is the issue.

**Comment by Duncaen** [comment]
If you set a restrictive umask and create files then its on you. the debug output shows you what can't be read and this is where the issue lies.
So change the configuration file permissions back to something sane like 644.
Also the configuration files in `/usr/share/xbps.d` have wrong permissions, no idea how this could happen without the user doing something unexpected. 
xbps itself sets the umask to 0022 while unpacking packages.

**Comment by edn9** [comment]
Oooh thats why I was getting this error, now everything is working alright, thank you guys for your support and for helping me out, sorry about the umask 0077, I'm still learning about hierarchy and permission. I'm glad that I understand what happen and how to solve it, thank you.
