### ISSUE TITLE
xbps-checkvers: first repo wins is not enough

### ISSUE THREAD

**Issue by xtraeme** [void-linux/xbps#154]
Consider the following example:

```
[juan@leysa void-packages]$ xbps-checkvers --repository=/mnt/storage/xbps/hostdir/binpkgs -D $PWD -sm clang
llvm8 8.0.0_4 8.0.0_5 clang /mnt/storage/xbps/hostdir/binpkgs
[juan@leysa void-packages]$ xbps-checkvers -D $PWD -sm clang
llvm8 8.0.0_5 8.0.0_5 clang https://alpha.de.repo.voidlinux.org/current/musl
[juan@leysa void-packages]$
```

Now that xbps-src has been switched to use xbps-checkvers there's this issue compared to the previous implementation.

If an old version of a package exists in the xbps-src local repository, it won't detect any other version registered in the other repos.

IMHO xbps-checkvers should check all repos and then find the one that matches the version requirement, not just checking in the first repo that has this pkg matched by its package name.

**Comment by Duncaen** [comment]
So something like `bestmatching`, should this be the default or a new flag? And is there maybe a use-case for where the current way is more correct because of how xbps-src prefers local packages?

**Comment by xtraeme** [comment]
The previous logic in xbps-src was:
- if pkg exists in local repo, use it
- if pkg exists in remote repo, use it
- fallback to srcpkgs otherwise

**Comment by xtraeme** [comment]
For xbps-src we'd want bestmatch enabled by default, I think

**Comment by xtraeme** [comment]
This is not an issue anymore, not interested on it.
