### ISSUE TITLE
xbps-checkvers: unexistent pkgs are ignored

### ISSUE THREAD

**Issue by xtraeme** [void-linux/xbps#155]
We'd need something like this for xbps-src to work correctly with the generated 32bit packages (right now gcc-multilib and others are broken):

```$ xbps-checkvers -D $PWD -sm glibc-32bit```

Currently unexistent packages in srcpkgs are simply ignored.

**Comment by Duncaen** [comment]
Hm we could make `-32bit` a special case, but I don't like that.

**Comment by Vaelatern** [comment]
Should we add symlinks for -32bit and -dbg while we are at it, and get rid of our fake-pkgs?

**Comment by xtraeme** [comment]
This is not relevant anymore, xbps-src does not need anything extra.
