### ISSUE TITLE
icu-libs dependency corruption

### ISSUE THREAD

**Issue by Duckxz** [void-linux/xbps#159]
xbps gives me
`MISSING: icu-libs>=64.2_1
Transaction aborted due to unresolved dependencies.`
on xbps-install -Suv

icu-libs is version 63.1_2 in repo

EDIT: i have wiped /var/db/xbps to have xbps redownload repo but still the same

**Comment by Duncaen** [comment]
There is no corruption.

There is currently a big build ongoing, the repository staging code does not work between different repositories, so something from a sub repository that was already rebuild against the new `icu-libs`.

https://build.voidlinux.org/waterfall

Nothing to do other than waiting.

If you want to install something or update something, look at the debug output and put the packages requiring `icu-libs>=64.2_1` on hold with `xbps-pkgdb -m hold $pkgname`.
