### ISSUE TITLE
Removing package with dependencies can take a long time.

### ISSUE THREAD

**Issue by Yardanico** [void-linux/xbps#16]
This was actually addressed in https://github.com/voidlinux/xbps/pull/290 but it was never merged.
How to reproduce:
1. `sudo xbps-install -Su kde5`
2. `sudo xbps-remove -R kde5` <- will use 100% CPU (on one core) for a very long (compared to other package managers) time:
```
<no output for 30 mins>
<output about removing packages>
```
Total time: `sudo xbps-remove -R kde5  1926.08s user 2.08s system 98% cpu 32:39.60 total`

**Comment by pullmoll** [comment]
I also see this and think a lot of time is spent in this line:
https://github.com/void-linux/void-packages/blob/master/common/xbps-src/shutils/pkgtarget.sh#L51

I tried to comment this line and packaging seems to work without it. I don't know what it is good for and if it is required (in certain cases only?), though.

The dependency depth of KDE5 packages __is__ huge and removing packages will take much more time than say removing a single level of a few small packages.

**Comment by Yardanico** [comment]
@pullmoll I know it's huge but it's still strange that it can take 30 mins(!)

**Comment by veksha** [comment]
I think method `collect_rdeps` (at `lib/package_fulldeptree.c:47`) is going into infinite recursion (or maybe not infinite but VERY LONG).
Can't remove kde5 with -R parameter.

**Comment by Yardanico** [comment]
@veksha as I said, it's very long but it worked for me after ~30 mins

**Comment by yshui** [comment]
Recursive removing is slow because xbps is using an inefficient data structure during DFS to keep track of what packages have been searched.

If there is already a hash table available in xbps, we should use that. Otherwise we should pull in some hash table implementation. I suggest https://github.com/troydhanson/uthash

**Comment by yshui** [comment]
`sortfulldeptree` also doesn't handle circular deps. Is circular deps impossible with xbps?
