### ISSUE TITLE
tint2/virtualbox window bug

### ISSUE THREAD

**Issue by vileator** [void-linux/xbps#170]
I've tint2-16.7_1 and virtualbox-6.0.12_1 installed and running, but when the tint2 panel shows/hides from the mouseover event the virtualbox windows get shifted down and right a few pixels(the windows still keep their same WxH dimensions), and doing this may times eventually moves all the virtualbox windows to the bottom right corner of screen. This behavior doesn't affect the window when it's rolled up or minimized though. Attached is my tint2 config.

[tint2rc.txt](https://github.com/void-linux/xbps/files/3652319/tint2rc.txt)

**Comment by Duncaen** [comment]
This should be opened in https://github.com/void-linux/void-packages, this repository is for the package manager itself.
