### ISSUE TITLE
Make it possible to install restricted packages with xbps-install

### ISSUE THREAD

**Issue by crocket** [void-linux/xbps#18]
Installing several packages through xbps-src and upgrading them is tiresome because it doesn't integrate with xbps-install.

* adobe-flash-plugin
* vivaldi
* google-chrome

This is the reason that I migrated from void linux to artix linux.

On Artix Linux, I can manage AUR packages and binary packages with yay or other AUR helpers. yay handles both repositories seamlessly.

xbps needs one tool to manage all packages.

**Comment by Vaelatern** [comment]
We call it 'xi'.
We can not build restricted packages for you, as a matter of legality.

**Comment by crocket** [comment]
I read /usr/bin/xi, but it doesn't automatically build restricted packages through xbps-src.

**Comment by Vaelatern** [comment]
@crocket you can script this without difficulty.
