### ISSUE TITLE
Package being removed in transaction still triggers conflict

### ISSUE THREAD

**Issue by st3r4g** [void-linux/xbps#186]
Suppose you want to perform a transaction where a new pkg that conflicts with a currently installed pkg is installed, and at the same time the conflicting pkg gets removed (e.g. because replaced by another pkg). This is not possible because `"remove"` is not listed here:
https://github.com/void-linux/xbps/blob/be05118aa8adb9f2520c679c8649ce76eea28858/lib/transaction_conflicts.c#L91-L96
and `xbps` will error as if the conflict were not resolved.

**Comment by xtraeme** [comment]
Please provide a new test case to verify

**Comment by st3r4g** [comment]
Package setup:
```
xbps-create empty -n A-1.0_1 -s A -A noarch -C B
xbps-create empty -n B-1.0_1 -s B -A noarch
xbps-create empty -n C-1.0_1 -s C -A noarch -R B
```
Trying to perform a single transaction fails (but should be allowed):
```
xbps-install -r . --repository=. A C
CONFLICT: A-1.0_1 with installed pkg B-1.0_1 (matched by B)
Transaction aborted due to conflicting packages.
```
Doing separate transactions is allowed:
```
xbps-install -r . --repository=. C
Name Action    Version           New version            Download size
B    remove    1.0_1             -                      - 
C    install   -                 1.0_1                  - 
xbps-install -r . --repository=. A
Name Action    Version           New version            Download size
A    install   -                 1.0_1                  - 
```

**Comment by xtraeme** [comment]
I've experienced this with the recent mesa/nvidia changes.

I'll try to create a new test case and apply your fix.

**Comment by xtraeme** [comment]
finally got a test case to reproduce this issue!
