### ISSUE TITLE
Overall progress bar or percentage when downloading

### ISSUE THREAD

**Issue by mbarbar** [void-linux/xbps#187]
A progress bar showing how much has been downloaded overall would be nice. Currently, when I want to know how much has been downloaded, I kill xbps and start it again.

I'm happy to implement it. If there is interest, I have two concerns:

1. It seems to me that the total downloaded data, across packages, is not kept anywhere. Assuming I just couldn't find that info, it seems the most appropriate (global) place to store this would be in the `transd` dictionary in `xbps_handle`. Is there a better place?

2. I see two possibilities with respect to UI.

* At the beginning of the download lines, for example,
```
[  7%]pkg1.x86_64.xbps: [723KB 0%] 25MB/s ETA: 00m00s
...
...
[ 54%]pkg30.x86_64.xbps: [723KB 0%] 25MB/s ETA: 00m00s
```

* Underneath the download/verifying signature line. It would then always be the final line of the output. For example,

 ```
pkg2.x86_64.xbps: [723KB 0%] 25MB/s ETA: 00m00s
[  9% ***---------------------------]
...
...
pkg25.x86_64.xbps: [723KB 0%] 25MB/s ETA: 00m00s
[ 34% **********--------------------]
```

**Comment by xtraeme** [comment]
Sounds good, do you have a patch? :+1:

**Comment by xtraeme** [comment]
I prefer the second option (underneath)

**Comment by mbarbar** [comment]
Caught up with work till ~mid January, hopefully a little earlier, then I'll get into it.

**Comment by sineemore** [comment]
> It seems to me that the total downloaded data, across packages, is not kept anywhere.

@mbarbar transaction dictionary has "total-download-size" key.
@xtraeme is it the value we should use?

**Comment by sineemore** [comment]
Seems like on possible problem with storing this in transaction dictionary, is that it is immutable.

**Comment by xtraeme** [comment]
`total-download-size` is the right obj

**Comment by xtraeme** [comment]
https://github.com/void-linux/xbps/blob/master/lib/transaction_prepare.c#L92

**Comment by xtraeme** [comment]
I see what's the problem, `dlsize` is only incremented with `xhp->flags & XBPS_FLAG_DOWNLOAD_ONLY`. I'm adding a fix

**Comment by xtraeme** [comment]
The transaction dictionary now contains proper info, including `total-download-size`.

**Comment by xtraeme** [comment]
#230 implements the first suggested option shown in this PR.

And it seems to be good enough.

**Comment by xtraeme** [comment]
Note that we had this already via `total-download-size` and `total-download-pkgs` number objs in the transaction dictionary, but were skipped due to the introduction of `XBPS_FLAG_DOWNLOAD_ONLY`.

Fixed with these two commits:

- https://github.com/void-linux/xbps/commit/1b9dc3cc4dab73cc9218067c91cc96b21555b239
- https://github.com/void-linux/xbps/commit/4d6d328c62936c0bcd069ecfa146fb9cded21747

**Comment by xtraeme** [comment]
#230 has been merged. This is now implemented as suggested in the first method.

**Comment by mbarbar** [comment]
Thanks for this. I had a partial implementation but got slowed down by work.
