### ISSUE TITLE
repos not working

### ISSUE THREAD

**Issue by veksha** [void-linux/xbps#20]
Pinging alpha.de.repo.voidlinux.org works fine:

$ ping alpha.de.repo.voidlinux.org
PING vm1.a-lej-de.m.voidlinux.org (148.251.199.112) 56(84) bytes of data.
64 bytes from build.voidlinux.eu (148.251.199.112): icmp_seq=1 ttl=53 time=36.3 ms
64 bytes from build.voidlinux.eu (148.251.199.112): icmp_seq=2 ttl=53 time=57.10 ms
64 bytes from build.voidlinux.eu (148.251.199.112): icmp_seq=3 ttl=53 time=34.9 ms
64 bytes from build.voidlinux.eu (148.251.199.112): icmp_seq=4 ttl=53 time=46.6 ms

but xbps-install is failing:

$ sudo xbps-install -Syu
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Connection timed out

**Comment by the-maldridge** [comment]
There's a rebuild in progress and nginx is swapped out.  Feel free to use another mirror in the meantime.
