### ISSUE TITLE
[Nit picking] Github project description links to a page that redirects back to Github

### ISSUE THREAD

**Issue by silvernode** [void-linux/xbps#207]
Just a little oddity that I noticed and decided to poke at. I expected to see a nice page about xbps over at voidlinux.org, but instead I got the same page I was already looking at. I would suggest just removing the URL unless there is indeed a page to link to.

**Comment by xtraeme** [comment]
Sounds good

**Comment by xtraeme** [comment]
@Duncaen ?

**Comment by Duncaen** [comment]
Should this link to https://voidlinux.org/usage/xbps/?

**Comment by xtraeme** [comment]
yes

**Comment by Duncaen** [comment]
Ok, done.
