### ISSUE TITLE
xbps-query -o should follow symlinks

### ISSUE THREAD

**Issue by illiliti** [void-linux/xbps#210]
```
xbps-query -o /bin/id # empty result
xpbs-query -o /usr/bin/id # good result
```

**Comment by Duncaen** [comment]
* using `realpath(3)` on the argument 
   * breaks if the root directory is not `/`.
   * breaks the usecase of looking up the package owning a symlink.
   * doesn't work well with `--regex`.
* actually trying to match every path element against symlinks in the files.plist
   * Its complicated compared to what is done currently. You would have to read the files.plist of all packages, while the current implementation can just look up each files.plist one by one and exit early if a match is found. You have relative, absolute and dangling symlinks that all have to be handled.

And both solutions in combination with `-R` are unusable.

You can already do `xbps-query -o $(realpath /bin/id)` like the first solution would do, but without introducing side effects.

I don't think the added complexity of resolving symlinks is worth it.

**Comment by Vaelatern** [comment]
And if you want you can use `xlocate bin/id$`

**Comment by illiliti** [comment]
@Vaelatern Thanks for advice
@Duncaen I agree with you, complexity in this case is not solution. I suppose we need warning message because empty output is confusing. What do you think?

**Comment by Vaelatern** [comment]
No need, users just should use xlocate for most of their use cases.

**Comment by illiliti** [comment]
Okay, thanks anyway for clarify
