### ISSUE TITLE
Replace mechanism not working correctly anymore

### ISSUE THREAD

**Issue by st3r4g** [void-linux/xbps#218]
This can be reproduced by trying to perform a system update on the current (20191109) lxde live iso. XBPS 0.58 is unable to perform the update (specifically, is unable to replace lib{GL,EGL,...} with libglvnd) with the following error:
```
[DEBUG] Package `libGL-19.2.2_1' will be replaced by `libglvnd-1.3.0_1', matched with `libGL>=0'
[DEBUG] Package `libEGL-19.2.2_1' will be replaced by `libglvnd-1.3.0_1', matched with `libEGL>=0'
libgbm-19.3.3_1 (update) breaks installed pkg `libEGL-19.2.2_1'
libglapi-19.3.3_1 (update) breaks installed pkg `libEGL-19.2.2_1'
libglapi-19.3.3_1 (update) breaks installed pkg `libGL-19.2.2_1'
Transaction aborted due to unresolved dependencies.
```
xbps correctly detects the packages to be replaced but still complains about packages that should however be removed by the transaction.
I believe this is a regression in xbps because XBPS 0.57.1 can perform the update.

**Comment by xtraeme** [comment]
I see, will take a look at it this evening

**Comment by Duncaen** [comment]
I added a testcase and reverted the change that introduced the regression for now, that fix isn't as important as the libglvnd stuff.

**Comment by xtraeme** [comment]
Cool. Will see tomorroq

**Comment by xtraeme** [comment]
Already fixed.
