### ISSUE TITLE
xbps-remove -R removes manually installed deps

### ISSUE THREAD

**Issue by travankor** [void-linux/xbps#234]
Not sure if this reproducible for other people, but:
```
doas xbps-install ffmpeg
doas xbps-install geeqie
doas xbps-remove -R geeqie
```
results in xbps wanting to remove ffmpeg, which was manually installed.

After installing `geeqie`, `xbps-query -m` still has `ffmpeg` in the list. Also, if I do `xbps-remove geeqie` with no flags, `ffmpeg` is not considered an orphan.

**Comment by xtraeme** [comment]
please try with up-to-date master

**Comment by xtraeme** [comment]
also, you can use `-n, --dry-run` that doesn't need root perms and will give us the expected result

**Comment by xtraeme** [comment]
I want `xbps-foo -V` output, of the affected command, and debug output with `-d`

**Comment by travankor** [comment]
Current xbps is whatever is latest in the repos (not master):
```
xbps-remove -V
XBPS: 0.58 API: 20200118 GIT: UNSET
```

**Comment by travankor** [comment]
`xbps-remove -dnR geeqie`
http://ix.io/2cii

**Comment by xtraeme** [comment]
This is not good, you should have the same result than I do:

```
[juan@leysa void-packages]$ xbps-query -V
XBPS: 0.59 API: 20200221 GIT: a16e695d
```

See https://github.com/void-linux/xbps#building-and-testing-for-dummies

**Comment by travankor** [comment]
Bug still seems present on master.
```
xbps-query -V
XBPS: 0.59 API: 20200221 GIT: a16e695
```

```
xbps-remove -dnR geeqie
http://ix.io/2cin
```

**Comment by Duncaen** [comment]
`xbps_dictionary_get_bool` (`prop_dictionary_get_bool`) doesn't set the boolean if the object in the dictionary is not a boolean (or doesn't exist).
The code doesn't check the return value of it and therefor `automatic` will be always be true when it finds a one package that is automatically installed in the revdeps and then considers all following packages in the revdeps automatically installed.

https://github.com/void-linux/xbps/blob/master/lib/package_orphans.c#L181
```
	for (unsigned int i = 0; i < xbps_array_count(array); i++) {
		︙
		bool automatic = false;
		︙
		xbps_dbg_printf(xhp, " processing rdeps for %s\n", pkgver);
		for (unsigned int x = 0; x < xbps_array_count(rdeps); x++) {
			︙
			xbps_dictionary_get_bool(deppkgd, "automatic-install", &automatic);
			if (!automatic) {
				xbps_dbg_printf(xhp, " rdep %s skipped (!automatic)\n", deppkgver);
				continue;
			}
			︙
		}
	}
```

the automatic boolean is defined outside of the loop and set to false, if inside

**Comment by Duncaen** [comment]
Its a regression from this [commit](https://github.com/void-linux/xbps/commit/8a0c3032b70e4a3a308682e93b599bffabd73939#diff-f3a9572aef87e67414fe5f343606769dL102), it used to set `automatic = false`, before `xbps_dictionary_get_bool`.

**Comment by xtraeme** [comment]
Oh, I see.

**Comment by xtraeme** [comment]
@travankor please test

**Comment by xtraeme** [comment]
@Duncaen thx for the analysis! the error was really obvious but didn't find it until you said so :-)

**Comment by xtraeme** [comment]
@Duncaen please merge this one into the void pkg and sync xbps-static.

**Comment by Duncaen** [comment]
Pushed it, going to make new static archives tomorrow, chromium is queued.

**Comment by xtraeme** [comment]
thanks!

**Comment by travankor** [comment]
yep, it's fixed. Thanks xbps devs!

BTW @xtraeme, I'm curious, is there a reason for no test case for this?

**Comment by xtraeme** [comment]
@travankor was too tired yesterday, will make one today :-)

**Comment by xtraeme** [comment]
https://github.com/void-linux/xbps/commit/0005b3ecc08ef3f1979b49f665bb06ef02d10080
