### ISSUE TITLE
[Feature request]: Warn the user to remove the previous kernel version after kernel's updated

### ISSUE THREAD

**Issue by marek-lach** [void-linux/xbps#236]
A simple message like: Kernel updated. Remove previous kernel version using `vkpurge` would be so helpful for new users like me who sometimes forget to do that :-)

Thanks,

**Comment by Duncaen** [comment]
Generally users don't read update messages unless something goes wrong, this is why we try to not use `INSTALL.msg` anymore and had to post a blog post about the OpenSSH update.

Adding more "useless" update/installation messages will just make more users to ignore the messages.

**Comment by xtraeme** [comment]
I agree
