### ISSUE TITLE
xbps-install "Segmentation fault"

### ISSUE THREAD

**Issue by jackg2** [void-linux/xbps#242]
I was performing an xbps-install update:

  xbps-install -Su:  xbps must be updated
  xbps-install -u xbps:  0,=.58_3 -> 0.59_1
  xbps-install -u:  108 packages will be downloaded
                  4 packages will be installed
                  Segmentation fault

the only way I could proceed was to create a script to update the individual packages, one-by-one.  After that:

  xbps-install -u:  installed 18 more packages [in one go]

Updating a different computer with only 41 packages needing update went OK.  Bug?

kernel 5.4.17_1 [musl x86_64]

**Comment by xtraeme** [comment]
not enough info, next time use `-d` to get debug output

**Comment by jackg2** [comment]
I did run the command with "-ud" but I don't think I should include 7800 lines of text here.  Is there anything I could extract from the debug monster?  If so I can transfer it from the development computer to this one.

**Comment by xtraeme** [comment]
use `wgetpaste`

**Comment by jackg2** [comment]
I found the wgetpaste binary not help is missing.  I have no clue what it does.   Is the intention that I insert the text here? Or is there another way of including it [that I cannot see]?

**Comment by xtraeme** [comment]
`wgetpaste` is a solution, you can use any other paste site or utility...

**Comment by jackg2** [comment]
OK, if you want me to paste 7800 lines of text HERE, please confirm [I feel uneasy pasting such large texts].  Thanks.

**Comment by xtraeme** [comment]
read above again, I'm suggesting you to use a "paste site" not pasting this directly into github...

**Comment by jackg2** [comment]
sorry, I will put it up on pastebin.com [few hours as I have to go]._

**Comment by jackg2** [comment]
I posted most of it on pastebin.com account "picamanic", file "xbps-debug" [I had to cut 2000 lines from middle as I exceeded free quota].  I hope that helps.

**Comment by xtraeme** [comment]
how about pasting the url here?

**Comment by jackg2** [comment]
I think it is https://pastebin.com/jVAatQK6

**Comment by xtraeme** [comment]
please share the output of `xbps-install -und`, no need to run it as root.

**Comment by Duncaen** [comment]
There should be an xbps update available, if you can't just update xbps make sure the terminal window is large, this should work around the bug.

**Comment by jackg2** [comment]
I can no longer run the command as I fixed the problem by running the xbps-install -udy commands for each package individually in a script [as explained above;  I did this before posting here].  The pastebin file is the evidence.  I don't understand why output to an xfce4-terminal should crash xbps-install when updating 108 packages but not others.

**Comment by Duncaen** [comment]
It happens if there are more than at least three packages being updated, the terminal has less than I think 80 columns and the update alternates between "update", "install" and "update" again.

The issue is fixed in xbps and there is an updated xbps package available in void linux that includes the patch.

**Comment by jackg2** [comment]
OK, thanks for the explanation.  If it happens again, I will make more columns [normally, only linux kernel "make menuconfig" complains about <82-cols].
