### ISSUE TITLE
Global updates randomly refused in certain conditions

### ISSUE THREAD

**Issue by Chocimier** [void-linux/xbps#245]
There is a bug in xbps_transaction_check_revdeps that goes like this:

1. Get libX that is updated, set ttype=update.
2. Start looping over revdeps of libX.
3. Take revdep cmdA that is removed, set ttype=remove.
4. Take revdep cmdB that is up to date.
5. libX is removed, but cmdB stays installed. Error!

Will fix tomorrow if noone want take it earlier.

Edit for recognizability: update failed with `libX-1_2 in transaction breaks installed pkg cmdB-1_1'`.

**Comment by Duncaen** [comment]
The fix is wrong/incomplete...

**Comment by Duncaen** [comment]
This whole things doesn't make a lot of sense...

**Comment by Duncaen** [comment]
The right fix breaks #218 again.

**Comment by xtraeme** [comment]
No test case?

**Comment by xtraeme** [comment]
Thanks for the fix for the fix :-)

So looks like this is another case that wasn't tested before and it worked by luck, because there's no test case.

**Comment by Duncaen** [comment]
I can try to come up with a testcase.

Maybe it would be nice to create a separate repository for more "real world" test cases where we store package database snapshots of real world installations from ISOs etc and then add snapshots from the repository databases whenever there are "bigger" changes.

Or maybe we could write a script to help to minimize pkgdbs and repodatas for new test cases.

**Comment by xtraeme** [comment]
I'm all for it

**Comment by Chocimier** [comment]
Fixed in 0.59_5. I could do testcase too if you didn't started, transcribed description should be one.

**Comment by Duncaen** [comment]
I didn't start, I guess we could add a bunch of common scenarios to the shell update install tests with more dependencies, they all looked very basic like A depends on B we could probably use some more long/deep dependency chains.

**Comment by Chocimier** [comment]
Submitted one test. Real-world test and small thought out ones makes more sense to me that fuzzing.

**Comment by xtraeme** [comment]
fixed by @duncaen via https://github.com/void-linux/xbps/commit/044f75450bf80a5434097385cec90715c8655c6f

test case by @Chocimier in #246
