### ISSUE TITLE
segfault on invalid local repodata file

### ISSUE THREAD

**Issue by lordwelch** [void-linux/xbps#248]
I believe commit 835834ff73585ce38d1ae0416865b8c1b45777c9 introduces a segfault by calling xbps_repo_close twice once on either repo.c line [159](https://github.com/void-linux/xbps/blob/a46e17971689e47b26e9744e3f63f32b983be307/lib/repo.c#L159) or [167](https://github.com/void-linux/xbps/blob/a46e17971689e47b26e9744e3f63f32b983be307/lib/repo.c#L167) and again on line [259](https://github.com/void-linux/xbps/blob/a46e17971689e47b26e9744e3f63f32b983be307/lib/repo.c#L259) as currently the only place that `repo_open_local` is referenced is line [252](https://github.com/void-linux/xbps/blob/a46e17971689e47b26e9744e3f63f32b983be307/lib/repo.c#L252)

this is reproducible by running
```
truncate --size 0 /var/db/xbps/$REPOSITORY/$ARCH-repodata
xbps-install -u
```

**Comment by xtraeme** [comment]
indeed, thanks for the detailed info. Fixed
