### ISSUE TITLE
'latest' xbps-static compile for i686 can't find packages

### ISSUE THREAD

**Issue by mcewanw** [void-linux/xbps#250]
The latest xbps-static compile for i686 is version 0.51_1. I find that whilst i686-repodata gets downloaded after xbps-install.static -Su, no packages are actually thereafter found when trying to install them (e.g. xbps-install -Suy xbps-triggers base-files). I can only presume that this 0.51_1 version is too old and needs updated (?)

wiak

**Comment by Chocimier** [comment]
We have no i686-musl toolchain, but what about cross-compiling from x86_64? It's quite fast. Or is there some different problem?

**Comment by Duncaen** [comment]
I added a build, but I was only able to briefly test it on a x86_64 system.

**Comment by mcewanw** [comment]
Your build seems to be working fine for me on my [XenialDog32](http://murga-linux.com/puppy/viewtopic.php?t=106696) i686 host system, Duncan. Many thanks.

**Comment by xtraeme** [comment]
no issue
