### ISSUE TITLE
can't boot void after system upgrade

### ISSUE THREAD

**Issue by erdosnew** [void-linux/xbps#252]
hi, i upgraded my system but couldn't start the system after reboot

the systems displays the following then freezes:
'Booting Void GNU/Linux

Loading Linux 5.4.25_1...
Loading initial ramdisk..'

I updated system from a previous 'xbps'  < 0.54, related thread is here
https://github.com/void-linux/xbps/issues/251
the system is a homebuilt pc with void installed on internal IDE drive.

any advice?

**Comment by xtraeme** [comment]
unrelated to xbps, ask for help in the forum
