### ISSUE TITLE
Improving INSTALL/REMOVE scriptlets

### ISSUE THREAD

**Issue by Duncaen** [void-linux/xbps#254]
At the moment INSTALL with "pre" parameter runs within the transaction before the package is being unpacked.
Currently there is also a bug where this is run after obsolete files are removed, potentially breaking the script.
In general I think this should run before unpacking any packages, similar to the configure step which runs INSTALL with "post" parameter after all packages are unpacked.

Changing this would avoid breaking the INSTALL scripts in between packages are being unpacked,
one example I know that broke a lot of things was the readline+bash update for users that had bash as `/bin/sh` alternative.

I think some script runs can also abort the transaction, which shouldn't happen, packages with failing scriptlets should be marked as `XBPS_PKG_STATE_UNPACKED` and `XBPS_PKG_STATE_HALF_REMOVED`.

I think another improvement we should add is passing to the scriptlets if we are being chrooted or not to allow the scriptlets to exit unsuccessful, marking the package as unpacked/half-removed if we can't make the scriptlets use relative paths, i.e. they are running some program that doesn't support that and not just chmod/chown/mkdir/rm.

**Comment by Duncaen** [comment]
`REMOVE` scripts have `pre`, `post` and `purge` options, I think for simplicity its best to remove `purge` as there is no real difference to `post` only that purge reruns if the package was half removed which can only happen if `purge` fails to run lol.

**Comment by xtraeme** [comment]
the `purge` action had too many changes in these years... I don't even remember what's the point of it. But probably we could clean up all them... so I'm really open for new ideas and fixes.

**Comment by xtraeme** [comment]
I think we could replace all scriptlets with a new hooks implementation. This should cover all cases easily. And have the scriptlets support specifically for X pkgs.

**Comment by Duncaen** [comment]
Yes I tried to track down the origin of purge, this is the last commit I looked at: https://github.com/void-linux/xbps/commit/3b7491d29.

I think hooks would be a good way to get rid of most of the current triggers and could reduce the installation speed by a lot if they can collapse i.e. font cache stuff into one run.

I also think some things like `make_dirs` could be moved into xbps if we add chown by user and group names to xbps.

**Comment by xtraeme** [comment]
@Duncaen I agree, make_dirs should be part of xbps. Also I think xbps should track uid/gid and permissions.

**Comment by Chocimier** [comment]
Another reason to move `make_dirs` to xbps is that now directories created like that can be removed, potentially misconfiguring permissions.

Example:

    xbps-install logrotate
    ls -a /etc/logrotate.d
    xbps-install bind
    xbps-remove bind
    ls -a /etc/logrotate.d
