### ISSUE TITLE
xbps-create wont set pkgver to anything other than foo

### ISSUE THREAD

**Issue by constatinus** [void-linux/xbps#262]
Typing something like, no matter the pkgver
` % xbps-create destdir -n pkg-1.0.0 -s whatever -A x86_64`
yields
``xbps-create: ERROR: invalid pkgver! got `pkg-1.0.0' expected `foo-1.0_1'``
And it only works when i set it to foo-1.0_1, which is a part of the example command that prints out when typing `xbps-create -h`, which does create the file as foo-1.0_1.x86_64.xbps

**Comment by pullmoll** [comment]
Did you try `xbps-create destdir -n pkg-1.0.0_1 -s whatever -A x86_64` i.e. include a revision `_1` in the pkg version?

**Comment by xtraeme** [comment]
As @pullmoll said above you are trying to use an invalid pkgver.

Not an issue

**Comment by pullmoll** [comment]
Perhaps `xbps-create`'s error message could be a tad more explicit and tell why the pkgver is invalid; if it knows why that is.

**Comment by constatinus** [comment]
Yes, that was the issue it seems, thank you.
