### ISSUE TITLE
xbps-query with XBPS_ARCH and XBPS_TARGET_ARCH has confusing behavior

### ISSUE THREAD

**Issue by st3r4g** [void-linux/xbps#264]
`Void 5.4.30_1 x86_64-musl GenuineIntel uptodate rrnFFFFF`
`XBPS: 0.59.1 API: 20200221 GIT: UNSET`

- `XBPS_ARCH=x86_64 xbps-query --repository=https://alpha.de.repo.voidlinux.org/current/nonfree -Md steam` cannot find the pkg, and:
```
[DEBUG] Architecture: x86_64-musl
[DEBUG] Target Architecture: (null)
```

- `XBPS_TARGET_ARCH=x86_64 xbps-query --repository=https://alpha.de.repo.voidlinux.org/current/nonfree -Md steam` can find the pkg, but:
```
[DEBUG] Architecture: x86_64-musl
[DEBUG] Target Architecture: x86_64-musl
```
Why `XBPS_ARCH` and `XBPS_TARGET_ARCH` have different behavior here, while the man page says the only difference is that `xbps-install` will skip configuration phase? And why the debug log doesn't report the modified arch correctly?

Other tests with `xbps-install`:
- `XBPS_ARCH=x86_64 xbps-install --repository=https://alpha.de.repo.voidlinux.org/current -r /tmp/test -Sd glibc`
```
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
```
- `XBPS_TARGET_ARCH=x86_64 xbps-install --repository=https://alpha.de.repo.voidlinux.org/current -r /tmp/test -Sd glibc`
```
[DEBUG] Architecture: x86_64-musl
[DEBUG] Target Architecture: x86_64-musl
```
Here, the pkg is found in both cases.

**Comment by xtraeme** [comment]
Hmm this worked at some point... it's a real bug! XBPS_ARCH should be enough.

**Comment by xtraeme** [comment]
in lib/transaction_commit.c:

```
        if (xhp->target_arch && strcmp(xhp->native_arch, xhp->target_arch)) {
                /* if installing packages for target_arch, don't configure anything */
                goto out;
                /* do not configure packages if only unpacking is desired */
        } else if (xhp->flags & XBPS_FLAG_UNPACK_ONLY) {
                goto out;
        }
```

So that configuration phase is only skipped if XBPS_TARGET_ARCH is set, and != XBPS_ARCH.

**Comment by xtraeme** [comment]
Also there's `xbps-install -U` to only unpack.

**Comment by xtraeme** [comment]
I think the manpages are ok:

```
     XBPS_ARCH               Overrides uname(2) machine result with this
                             value. Useful to install packages with a fake
                             architecture.

     XBPS_TARGET_ARCH        Sets the target architecture to this value. This
                             variable differs from XBPS_ARCH in that it allows
                             you to install packages partially, because
                             configuration phase is skipped (the target
                             binaries might not be compatible with the native
                             architecture).
```

**Comment by xtraeme** [comment]
I think this one is now fixed, there was a typo in debug messages that wasn't showing correct results.

The behaviour is ok (has always worked this way for years).
