### ISSUE TITLE
xbps-install -Su does not inform about packages on hold

### ISSUE THREAD

**Issue by svenper** [void-linux/xbps#265]
(moved from https://github.com/void-linux/void-packages/issues/20130)

### System

* xuname: `Void 5.4.25_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFFF`
* package:  `xbps-0.59_5`

### Expected behavior

`xbps-install -Su` informs about packages on hold as it used to

### Actual behavior

```text
# xbps-install -Su
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
# xbps-install -S firefox
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...

Name      Action    Version           New version            Download size
firefox   update    73.0.1_1          74.0_1                 57MB
...
```

### Steps to reproduce the behavior

```text
# xdowngrade /var/cache/xbps/firefox-73.0.1_1.x86_64-musl.xbps
# xbps-pkgdb -m hold firefox
# xbps-install -Su
# xbps-install -S firefox
```

**Comment by xtraeme** [comment]
```
commit 66b856fa77dd8535c0174be4150029c76de591cc
Refs: 0.57.1-19-g66b856fa
Author:     Mohamad Barbar <mbarbar@runbox.com>
AuthorDate: Tue Dec 10 21:26:26 2019 +1100
Commit:     Juan RP <xtraeme@gmail.com>
CommitDate: Sat Dec 14 13:23:31 2019 +0100

    xbps-install: don't prompt when all pkgs on hold.
```
This was added to 0.58, because it was useless to prompt if all packages in transaction are on hold.

Why is this a bug? I think this new behaviour is consistent.

**Comment by travankor** [comment]
It doesn't prompt when some pkgs are on hold, too. 

I'm not sure if this is bad or good, though.

**Comment by svenper** [comment]
What I meant is that there is indeed no need to prompt, but it should still list the packages with updates available.

**Comment by xtraeme** [comment]
hmm indeed, this seems to be a regression then

**Comment by xtraeme** [comment]
http://dpaste.com/22H8RGW.txt

Please apply this one ^ on top of master and test!

**Comment by travankor** [comment]
the patch doesn't fix this issue, but `xbps-query -p hold bemenu` from the previous example now says yes (existing hold pkgs don't have this)

**Comment by xtraeme** [comment]
hold on, I'm working on a fix
