### ISSUE TITLE
No way to enable coverity

### ISSUE THREAD

**Issue by xtraeme** [void-linux/xbps#269]
Because I don't have admin rights I can't enable coverity scan in XBPS (which is my own code).

This is for admins in charge, I've wanted to enable coverity for a long time. I tried contacting the admins multiple times with no answer.

I'll wait for 1 week, if there's no progress I'll make xbps part of my user github account and this be will the main source.

https://scan.coverity.com/

**Comment by Duncaen** [comment]
I don't see how this can be enabled other than using [travis](https://scan.coverity.com/travis_ci) or the [github action](https://github.com/marketplace/actions/synopsys-detect).

**Comment by Duncaen** [comment]
https://scan.coverity.com/ says I need to be approved by the project owner ¯\\\_(ツ)_/¯
https://imgur.com/a/XJHkBz4

**Comment by xtraeme** [comment]
and who is the project owner? this is what bothers me!

**Comment by Duncaen** [comment]
oh wait this is the old repository

**Comment by Duncaen** [comment]
probably you for the old one, but it doesn't exist

**Comment by xtraeme** [comment]
ah right! voidlinux org is just empty

**Comment by Duncaen** [comment]
there should be an invite at xtr..@gm

**Comment by xtraeme** [comment]
ok, accepted. Could you please add stuff to README/gh actions whatever?

**Comment by Duncaen** [comment]
Hm I think we have to use the travis integration, but this seems kinda weird to configure https://scan.coverity.com/travis_ci, I think this doesn't really work with how we build in a docker container.

**Comment by xtraeme** [comment]
hmm

**Comment by Duncaen** [comment]
1 hour later and it now was scanned successfully.

**Comment by Duncaen** [comment]
I see that there are defects, but can't inspect them.

> While we review your project application you cannot view defects. It takes about 1-2 business day to review your association with the project and to make sure project meets open source guidelines.

**Comment by xtraeme** [comment]
let's wait

**Comment by xtraeme** [comment]
fixed by @Duncaen thanks!
