### ISSUE TITLE
Error while setting up void linux on zfs

### ISSUE THREAD

**Issue by ylabidi** [void-linux/xbps#291]
Hi,
Not sure if this is the right buck tracker to ask question on. I've trying to install void linux on a zfs root following this [guide](https://github.com/zdykstra/zfsbootmenu/blob/master/void-install.md). And I've hitting the following error when attempting the install:
```
xbps-install -S -R https://mirrors.servercentral.com/voidlinux/current -r /mnt base-system zfs vim efibootmgr gptfdisk
```
and could find a workaround or a solution for it:
```
glibc-2.30_1: unpacking ...
ERROR: glibc-2.30_1: [unpack] failed to extract file `./usr/bin/getconf': Invalid cross-device link
ERROR: glibc-2.30_1: [unpack] failed to extract files: Invalid cross-device link
ERROR: glibc-2.30_1: [unpack] failed to unpack files from archive: Invalid cross-device link
Transaction failed! see above for errors.
```

I also tried to unpack the `fsroot` archive instead of installing with `xbps` and still experiencing the same error.

Any help,suggestions, pointers, is appreciated.

**Comment by Vaelatern** [comment]
That's a new one. Sounds like a hardlink somewhere.

Also you may want to check out https://github.com/void-linux/void-docs/pull/206

**Comment by ylabidi** [comment]
Found a way around it. I unpacked the fsroot tarball to a temporary directory, then rsynced to the path I mount the zpool on. Didn't get any errors.

**Comment by ericonr** [comment]
huh, weird. As reference, I used https://github.com/zdykstra/zfsbootmenu/wiki instead. Not sure if there are any differences.

**Comment by ylabidi** [comment]
@ericonr 
> huh, weird. As reference, I used https://github.com/zdykstra/zfsbootmenu/wiki instead. Not sure if there are any differences.

I don't think the problem was with the guide. Rather my own zfs dataset hierarchy which involved more levels.
