### ISSUE TITLE
Install Packages to /usr/local

### ISSUE THREAD

**Issue by Druidpeter** [void-linux/xbps#297]
I have a small main ssd and a large secondary drive mounted on /usr/local. I want to make sure packages are installed to /usr/local so as to save space on my small ssd. I've scoured the man pages and I thought --rootdir was the option I needed to specify, but with that option set to /usr/local, I just keep getting "package not found" errors.

I can't seem to find anything about this elsewhere in the docs. Does anyone know howto do this?

**Comment by Duncaen** [comment]
This is not really xbps related, the path depends on how the packages are build.
In void linux, the packages are build with `/usr` as prefix and you can't really change that.
If you use a separate rootdir to install packages then the path will be `$rootdir/usr/local`.
