### ISSUE TITLE
Add a flag to automaticlly install devel packages with install

### ISSUE THREAD

**Issue by MrLazerbean** [void-linux/xbps#299]
Oftentimes I would like to be able to simply add a flag to automaticlly install `package-devel` when I install `package`.

**Comment by Chocimier** [comment]
`xbps-install {libA,libB}{,-devel}` in reasonable shells do that.

**Comment by ericonr** [comment]
Yeah, this looks like something that should at most be part of a wrapper... Specially because there isn't any formal relationship between packages and their devel version, for example: `mesa` and `MesaLib-devel`, and XBPS doesn't know that one is the development package of the other.

**Comment by MrLazerbean** [comment]
True, closing now
