### ISSUE TITLE
add config option for the location of the signature directory (or files)

### ISSUE THREAD

**Issue by hippi777** [void-linux/xbps#300]
hi there! :)

if i would like to install void from a different distro that i dont wanna mess with (i.e. dont install signatures globally), then i can only accept it like `echo yes | xbps-install`, and if i also wanna use a random 2nd tier mirror, then i must trust it, and also, if it only has http access, then i must trust in the network as well...

so actually i wish for making it fully portable, as the statically linked xbps is already a thing, it would be really nice imho :)

i think its not a big deal, but i know its kinda much of a corner-case, so its not urgent, but sooner-or-later i will reach that point when i will play with this in my new installer, and it would be nice if i could test things accordingly on the go

thx 4 any help! :)

**Comment by ericonr** [comment]
Look into how `xvoidstrap` does it, it copies those files into the proper place. You can find it here https://github.com/leahneukirchen/xtools/blob/master/xvoidstrap#L34

**Comment by hippi777** [comment]
thx! :) if thats not mistaken with using the keys of the host, but xbps will find them in the target dir, then its totally fine for me! especially if i dont need to mess with chroot for this step into an empty system with binds from the host that i also wouldnt like to get messy anyhow... :D btw i think _maybe_ i can totally leave out chrooting from the installation, and in that case things would be that much prettier  :D

**Comment by ericonr** [comment]
Yes, you will have to store the keys somewhere to move them there, but you have total freedom to choose that.

I am not sure the installation can be completeted without a chroot step, because some of the configuration steps have to be run from inside the system:

- system accounts creation hooks
- initramfs generation
- bootloader installation (perhaps)
- ...

**Comment by hippi777** [comment]
> you will have to store the keys somewhere
shipped with static xbps, thats fine, and thats still not a syswide install of them, so thats not an issue :)

nothing much important below; also, i just wondered about leaving out chroot, but i still think that maybe its possible :D

> system accounts creation hooks
hooks? :O what hooks? :D im not aware of any... if im right, then ive seen that setting up users+groups can get an option to specify the target root dir

> initramfs generation
if im right, then xbps-install will call the related hooks, and i think it shouldnt fail when `-r` is provided, but maybe that happens only if i run xbps-reconfigure from the chroot... i will need to try, but thats not for now... :D  

> bootloader installation (perhaps)
i know fixing grub is done via chrooting in most of the codes ive ever seen, but i think ive seen arguments to it to specify both the conf file and the installation target

**Comment by ericonr** [comment]
> hooks? :O what hooks? :D im not aware of any... if im right, then ive seen that setting up users+groups can get an option to specify the target root dir

Sorry, I meant triggers. They should be available in `/usr/libexec/xbps-triggers/`

**Comment by hippi777** [comment]
thx, i didnt know about that directory, its really useful, i only knew about /etc/kernel.d so far now :D and yep, the dracut postinstall seems to be like it requires a chroot :D otherwise ive meant that adding regular users for example have no hooks, cuz adduser is not related to the xbps tools... but never mind, thats the unimportant part :D 

however the issue is real:
```
# cp -R ./xbps-static-static-0.59_5.x86_64-musl/var /mnt
# env XBPS_ARCH=x86_64-musl ./xbps-static-static-0.59_5.x86_64-musl/usr/bin/xbps-install -Su -R https://alpha.de.repo.voidlinux.org/current/musl -r /mnt base-system
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
x86_64-musl-repodata: 1651KB [avg rate: 4598KB/s]
`https://alpha.de.repo.voidlinux.org/current/musl' repository has been RSA signed by "Void Linux"
Fingerprint: 60:ae:0c:d6:f0:95:17:80:bc:93:46:7a:89:af:a3:2d
Do you want to import this public key? [Y/n]
```

**Comment by ericonr** [comment]
I can't reproduce.

```
$ tar xfv xbps-static-static-0.59_5.x86_64-musl.tar.xz
$ mkdir -p chroot ; cp -R var/ chroot/
$ env XBPS_ARCH=x86_64-musl usr/bin/xbps-install.static -Sy -R https://alpha.de.repo.voidlinux.org/current/musl -r chroot/  base-system
```
Installs all packages without requiring any input.

**Comment by hippi777** [comment]
but i guess u tested it on void and it used the global keys

**Comment by ericonr** [comment]
I even tried renaming my local keys to see if that was the issue... I don't have a non void system to test this on.

**Comment by hippi777** [comment]
ehh, just wanted to suggest that :D but then ive got no idea why it differs on my (temporary) debian... :D maybe tomorrow i will try to test it on void

**Comment by hippi777** [comment]
u r right! somehow the key files werent there, but only the folders, even if i did it by root and cp -R just like now...... ive got no idea! :D however that means all good! :) thx very much! :)

**Comment by Duncaen** [comment]
`-y` doesn't automatically accept new keys, because this would allow an attacker to simply add a new key for malicious packages and attack anyone using `-Suy` to update their system.

**Comment by hippi777** [comment]
thx 4 the info! :)
