### ISSUE TITLE
empty line in mirror conf

### ISSUE THREAD

**Issue by veksha** [void-linux/xbps#32]
If file `/usr/share/xbps.d/00-repository-main.conf` contains no empty line at the end then mirror URL gets truncated and update fails.

**Comment by Vaelatern** [comment]
Files must have a newline at the end of the file. This is a standard on UNIX systems.
And the file you mention is not user configurable.
Is this true for other files read for repository information?

**Comment by xtraeme** [comment]
Already fixed, thanks
