### ISSUE TITLE
Search tags through xbps-query

### ISSUE THREAD

**Issue by dashezup** [void-linux/xbps#339]
> `tags` A white space separated list of tags (categories) that are registered into the package metadata and can be queried with `xbps-query` by users. Example for qutebrowser: `tags="browser chromium-based qt5 python3"`

[void-linux/void-packages/Manual.md](https://github.com/void-linux/void-packages/blob/master/Manual.md)

-t, --tags for xbps-create(8) [is added in 2014](https://github.com/void-linux/xbps/commit/b9e44009d9914294a19245f3c95f546529016277) but seems searching tags through xbps-query is not been implemented yet.

None of existing official packages use tags, but I tried to add tags to my packages in my own repo, `xbps-query -Rs <tag_name>` does not show packages with specific tags and `xbps-query -R <pkgname>` shows "tags" section of that package.

beside xbps-query -Rs show result of matched tags, having separate option (-t, --tags) for search tags only is also a good imo.

tags/categories could be useful when we need to search specific type of applications, such like "browser qt5 gtk xorg wayland" etc. I think this should be implemented and start tagging packages in official repo.

**Comment by Chocimier** [comment]
You can search tags with `xbps-query -R -p tags -s <tag_name>`

Discussion on tagging packages: https://github.com/void-linux/void-packages/issues/22191

**Comment by dashezup** [comment]
Thanks, I didn't know -s can be combined with -p before, that's very useful.
Since that's still under discussion, it's not necessary to have separate option or include in -Rs to search tags atm.
Close for now.
