### ISSUE TITLE
Feature request: option to ignore errors/"package not found" error

### ISSUE THREAD

**Issue by kazblox** [void-linux/xbps#367]
This is causing some automation issues with a script I am performing. I don't think there is a way to do this currently?

**Comment by ericonr** [comment]
Can you show what you're doing?

**Comment by kazblox** [comment]
Example:
`xbps-install -f pkg1 pkg2`
Let's say that pkg1 is not in any of my repos, but pkg2 is. However, by default [as it should be], pkg1 not being found force exits xbps-install, so it never gets to installing pkg2.

I would like to know if an option to at least skip a missing package would be viable.

**Comment by ericonr** [comment]
Sounds a bit error prone for usage, though I don't think it would be hard to implement. No idea about it being desired or not, though.

**Comment by Chocimier** [comment]
You can first construct list of existing packages in loop by looking at exit code of
     xbps-query maybe-package
, but make sure omitting packages will not hurt you.
