### ISSUE TITLE
ignorepkg does not work as declared

### ISSUE THREAD

**Issue by bcoolumbo1** [void-linux/xbps#369]
My input:
echo "ignorepkg=webkit2gtk" > /etc/xbps.d/20-ignore.conf
xbps-remove webkit2gtk

Rusult:
wxWidgets-gtk3-3.0.5.1_1: broken, unresolvable shlib `libwebkit2gtk-4.0.so.37'
Transaction aborted due to unresolved shlibs

I need wxWidgets-gtk3 for audacity, but don't want to update webkit2gtk, what to do?

**Comment by Vaelatern** [comment]
Maybe try not removing the package that provides the necessary package? I'm not sure what you expected would happen when you removed a package providing a library your system still needed.

**Comment by ericonr** [comment]
`ignorepkg` can only be used for packages that are added to `depends` manually, XBPS simply doesn't allow breaking dynamic libraries. Removing `webkit2gtk` from your system would simply break wxWidgets, and XBPS doesn't want to allow that. Maybe the man page needs to be clearer about it.

**Comment by bcoolumbo1** [comment]
Is it possible to just block the update and keep the old libs?

**Comment by Chocimier** [comment]
No, it will break eventually because soname will change. You may build your own wxWidgets-gtk3 with xbps-src with `--disable-webview`, if you find it better than not using webkit2gtk.

**Comment by superiums** [comment]
then how could we remove the pkg ?

i want to remove pkg: `linux-firmware-intel` which was dependented by `linux-base`, because i'm on AMD.
