### ISSUE TITLE
When executing xbps-pkjdb Ra , errors libcaribou

### ISSUE THREAD

**Issue by newtestonvoid** [void-linux/xbps#374]
: unexisten file /usr/lib/gnome-settings-daemon-3.0/gtk-modules/caribou-gtk-modules.desktop error libcaribou: files checked failed.   Void Linux cinnamon2019, zone/time applet can be set but not registering once it was set n closed.On running xbps-install -Suv showed no errors.  Any clues to rectify this. I m only a user not a developer. Appreciates any leads.      New void user

**Comment by Duncaen** [comment]
`xbps-install -f libcaribou`

**Comment by newtestonvoid** [comment]
Firstly, I would like to thank you for your kind inputs in such a fast respond, however, after executing :xbps-install -f libcaribou , after that I again issued : xbps-install -Suv shows no error, so I rebooted to check the timezone/time applet setting , it appeared the same. On issued the command again: sudo xbps-pkgdb -a  returns errors: Error: enchant: hash mismatch for /use/share/enchant/enchant.ordering. Error: enchant: files check failed.  Next line show: Error:Python alternative group Python symlink  /usr/bin/idle: No such file (same for /usr/bin/2to3; /usr/bin/Python; /usr/pydoc).        Sorry for this encounter as it may be lengthy. Any leads?  Appreciats all kind inputs .
