### ISSUE TITLE
Strange behaviour, maybe a bug?

### ISSUE THREAD

**Issue by tornaria** [void-linux/xbps#392]
### Steps to reproduce:

1. install old `pari` and `pari-devel` (version `2.11.4_1` which I have in my cache)
```
# xdowngrade /var/cache/xbps/pari{,-devel}-2.11.4_1.x86_64.xbps
```

2. Note that:
  - `pari-devel-2.11.4_1` depends on `pari-2.11.4_1`
```
$ xbps-query -S pari-devel | grep -P 'pkgver:|run_depends|\t'
pkgver: pari-devel-2.11.4_1
run_depends:
	pari-2.11.4_1
```
  - `pari-devel-2.13.1_1` depends on `pari>=2.13.1_1`
```
$ xbps-query -RS pari-devel | grep -P 'pkgver:|run_depends|\t'
pkgver: pari-devel-2.13.1_1
run_depends:
	pari>=2.13.1_1
```

3. Put `pari` on hold (currently installed version `2.11.4_1`)
```
# xbps-pkgdb -m hold pari
```

4. Do an update:
```
# xbps-install -u

Name       Action    Version           New version            Download size
pari-devel update    2.11.4_1          2.13.1_1               - 

[...]
```

5. Now `pari` is at `2.11.4_1`, but `pari-devel` is at `2.13.1_1`:
```
$ xbps-query -s pari
[*] pari-2.11.4_1       Fast computations library in number theory
[*] pari-devel-2.13.1_1 Fast computations library in number theory - development files
```

This is inconsistent with `pari-devel-2.13.1_1` depending on `pari>=2.13.1_1`.

### Expected behaviour

That holding `pari` at `2.11.4_1` prevents upgrading `pari-devel` to `2.13.1_1`, since that leads to an incosistent state.

I know I can hold `pari-devel`, but what if I forgot?

Ideally, it should ignore updating `pari-devel`, although an error is quite acceptable (because an error leads me to put `pari-devel` on hold, and then I'm happy and nothing has been broken).

---

### Another, similar behaviour:

1. have only `pari-2.11.4_1` installed and on hold
2. request install of `pari-devel`
3. xbps happily installs `pari-devel-2.13.1_1` without upgrading `pari-2.11.4_1`

I would have expected an error warning me that `pari-devel-2.13.1_1` cannot be installed.

Note in this case I cannot put `pari-devel` on hold beforehand so there's no workaround. OTOH, `xbps` has no recourse (since `pari-devel-2.11.4_1` is not in the repo) so there would be no choice but issue an error.

**Comment by Duncaen** [comment]
Should be fixed with https://github.com/void-linux/xbps/pull/393.
