### ISSUE TITLE
Add Support to Hidden Services

### ISSUE THREAD

**Issue by TNTBOMBOM** [void-linux/xbps#395]
Hi There, 

Im reading xbps capabalities: 

> Supports multiple local/remote repositories (HTTP/HTTPS/FTP).

What i see missing is the onion support, This is important for distros that focuses on anonymity like whonix or tails (so as the security path of download due to TLS/Clearnet DNS issues).

Debian-Apt support downloading packages over Tor and I2P hidden services:

apt-tor from official debian packages: https://packages.debian.org/buster/apt-transport-tor

apt-i2p from outside: https://github.com/eyedeekay/apt-transport-i2p , https://github.com/eyedeekay/apt-transport-i2phttp

Hope to see something similar at least supporting Tor onion services.

ThX!

**Comment by ericonr** [comment]
https://docs.voidlinux.org/xbps/repositories/mirrors/tor.html

We already support Tor.

**Comment by TNTBOMBOM** [comment]
cool , didnt see it.
