### ISSUE TITLE
xbps-install with --yes doesn't automatically import public key

### ISSUE THREAD

**Issue by Skaytacium** [void-linux/xbps#399]
When installing Void for the first time, xbps-install fetches the repo's public key, but with the `--yes` option, it still asks for the key. This is slightly annoying when scripting an installation, which I have. Thankfully, it's stderr, so redirecting to /dev/null can still be done even if it asks.

**Comment by Duncaen** [comment]
Yes this is 100% and the only way, you don't want mirrors to randomly add new keys and accept them.

**Comment by Skaytacium** [comment]
Oh, that's good to know, thanks for the detailed explanation.

**Comment by ericonr** [comment]
I think this should be added to void-docs and/or xbps man page.

**Comment by jpastuszek** [comment]
I was having the same issue (provisioning). I was looking for a tool e.g. `xbps-import-key` or something to import the key or a switch on `xbps-install`. Then looked into repository configuration file options for `public_key` or something like that to set the key. Finally `strace` reviled where `xbps-install` looks for the keys...

So adding one of the above (command, switch or configuration option) or documenting this in the https://docs.voidlinux.org/xbps/repositories/signing.html would be good for others to discover this.
