### ISSUE TITLE
xbps-install -U configures formerly unpacked packages

### ISSUE THREAD

**Issue by avdgrinten** [void-linux/xbps#408]
**How to reproduce**: Pick your favorite uninstalled package (here: `noto-fonts-emoji`). Run
* `xbps-install -fU noto-fonts-emoji`.
* As expected, `xbps-query noto-fonts-emoji` will show `state: unpacked`.
* Re-run `xbps-install -fU noto-fonts-emoji`. This will incorrectly *configure* the package even though `-U` is passed:

  ```
  0 downloaded, 0 installed, 0 updated, 1 configured, 0 removed, 0 on hold.
  ```
  Note that this is not only a visual bug, the `INSTALL` script does indeed run (e.g., running it under strace shows that `fc-cache` runs).
* `xbps-query noto-fonts-emoji` will now show `state: installed`.

**Comment by Duncaen** [comment]
The failing testcase https://github.com/void-linux/xbps/commit/05ff04a0fb86dfcec770260326a623b5a7d1f914 is related.

Any operation on a package that is in "unpacked" mode results in xbps doing configure on the next operation.

**Comment by Duncaen** [comment]
Merged the fixes.

**Comment by avdgrinten** [comment]
Thanks a lot for the help! It's great to have this resolved :+1: .
