### ISSUE TITLE
feature request: use xbps search with fzf  fazzy finder

### ISSUE THREAD

**Issue by ayoubelmhamdi** [void-linux/xbps#422]
i thank `xbps-query -Rs` it's best tool in `void-linux` , but it's not built-in with `fzf`  
if i want to search for firefox :
```
$ xbps-query -Rs firefox | fzf
```
but now i'm using this alias 
```bash
$ alias f="xbps-query -Rs"
$ f firefox | fzf
```
this alias is not powerful and not increment search in repo

**Comment by paper42** [comment]
You might be interested in https://github.com/zdykstra/fuzzypkg

**Comment by ayoubelmhamdi** [comment]
that tool that i need, thank's @paper42

**Comment by Duncaen** [comment]
I don't see anything here that xbps needs to add other than maybe allowing different output formats in xbps-query for which there is already #114.
