### ISSUE TITLE
Don't fatally warn insufficient disk space when --dry-run is used

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/xbps#424]
With `-n`, `xbps-install` should print all packages that need updating, even if there is insufficient disk space.

Currently xbps-installs quits, which makes it hard to figure out what the big packages to update are at all (and try to do a partial update).

**Comment by Chocimier** [comment]
Fixed in https://github.com/void-linux/xbps/commit/379cd4da2c375f09ce3d8f7e2282bd2e4df724a5

**Comment by leahneukirchen** [comment]
Good, can we have a release? ;)
