### ISSUE TITLE
armv8l architecture: can't find armv8l-repodata in aarch64 repository 

### ISSUE THREAD

**Issue by laserbat** [void-linux/xbps#43]
**Steps to reproduce**: on any armv8l device (android phone in my case) download aarch64 rootfs and try to update with `xbps-install -Su`.

**Expected results**: Update goes normally

**Actual results**: Update fails with this message
`[*] Updating https://alpha.de.repo.voidlinux.org/current/aarch64/armv8l-repodata' ...`
`ERROR: [reposync] failed to fetch file https://alpha.de.repo.voidlinux.org/current/aarch64/armv8l-repodata': Not Found`

**Workaround**: adding `export XBPS_ARCH=aarch64` to .profile fixes this problem

**uname output**:
`Linux localhost 3.18.112-Artemis #1 SMP PREEMPT Tue Jul 10 19:17:22 UTC 2018 armv8l GNU/Linux`

I guess it would be better to add feature to autodetect aarch64 architectures like armv8l and use correct repodata URL.

**Comment by Vaelatern** [comment]
Fascinating!

**Comment by jnbr** [comment]
you can try setting `architecture` in the config. See: https://github.com/voidlinux/xbps/issues/69

**Comment by the-maldridge** [comment]
I suspect that this is a bug in xbps-uhelper which is used to determine the CPU arch.

**Comment by jnbr** [comment]
I'd say this is the documented behavior. xbps uses the result of `uname(2)` as architecture.
A mapping from `armv8l` to `aarch64` would be wrong as `aarch64` support is optional for `armv8`.

**Comment by beginner3456789** [comment]
I had this problem with my occasionally used armv6l type raspberry pi zero after xbps install sync/update. Problem was empty /etc/resolv.conf fixed by setting in /etc/dhcpcd.conf file:

    static domain_name_servers=192.168.1.1
    sv restart dhcpcd

**Comment by xtraeme** [comment]
Hmmm this can be fixed easily. I know what's the issue

**Comment by xtraeme** [comment]
If arch == arm; then
  arch=armv8l
If 64bit; then
 arch=aarch64
fi
fi

**Comment by xtraeme** [comment]
I'll take a look at it soon.

**Comment by xtraeme** [comment]
I decided to not add any workaround in the code for this specific case.

You can set `XBPS_ARCH=aarch64` or a `xbps.d(5)` conf file with `architecture=aarch64`. So this is not too important.

Thanks for the info anyway!
