### ISSUE TITLE
xbps-install issue with bluez and blueman

### ISSUE THREAD

**Issue by nevillejackson** [void-linux/xbps#434]
If an xbps-install  -Su includes bluez-5.62_2 and blueman-2.2.3_1 it hangs with a message ...
ERROR: bluez-5.62_2: [unpack] failed to extract file `./etc/sv/bluetoothd/log/supervise': Directory not empty

There is a workaround. Do xbps-remove on bluez and blueman, remove the link /var/service/bluetoothd, empty the 'supervise' subdirectory, then reinstall bluez and blueman, and put the link back.
Then an xbps-install -Su will run to completion.

I had this issue on two separate computers, both Intel processors running 64 bit Void.

**Comment by Duncaen** [comment]
https://github.com/void-linux/void-packages/issues/33815

**Comment by nevillejackson** [comment]
Thank you Duncan,I followed the link to void-packages#33815The explanation is clear, and I agree we do not want xbps deleting untracked filesRegardsNevilleSent from Samsung tablet.
-------- Original message --------From: Duncan Overbruck ***@***.***> Date: 22/11/21  12:25 am  (GMT+10:00) To: void-linux/xbps ***@***.***> Cc: Neville Jackson ***@***.***>, Author ***@***.***> Subject: Re: [void-linux/xbps] xbps-install issue with bluez and blueman (Issue #434) 
Closed #434.
