### ISSUE TITLE
xbps-reconfigure: reconfigure dependencies

### ISSUE THREAD

**Issue by Duncaen** [void-linux/xbps#464]
Might be useful to reconfigure a package and its dependencies:

```
# xbps-reconfigure -fx linux
```

Would then also reconfigure the current kernel package, which would make it easier to document and run since you don't have to look up the version.

**Comment by classabbyamp** [comment]
should this reconfigure only direct dependencies or the full dep tree?

**Comment by Duncaen** [comment]
Could also add `--fulldeptree` to match `xbps-query`, but not sure how useful this is, not sure if there is a real usecase for it tho.
