### ISSUE TITLE
Unexpected result with Tier 1 repo address (00-repository-main.conf)

### ISSUE THREAD

**Issue by 2eb7a27b** [void-linux/xbps#467]
I spun up a fresh install of Void in a VM today utilizing the void-live-x86_64-20210930-xfce.iso, copied the **00-repository-main.conf** file from  **/usr/share/xbps.d/**  to  **/etc/xbps.d/**. Changed the default repo from `repository=https://alpha.de.repo.voidlinux.org/current`  to `repository=https://mirrors.servercentral.com/voidlinux/current`. Ran `xbps-install -Sv` to refresh the mirror, received an error stating the following:

> [*] Updating repository https://mirrors.servercentral.com/voidlinux/curren/x86_64-repodata ...
> ERROR: [reposync] failed to fetch file `https://mirrors.servercentral.com/voidlinux/curren/x86_64-repodata': Not Found

The xbps output is showing the repo address is missing the letter **_t_** from the word **_current_** at the end of the address. Verified in the **00-repository-main.conf** file the repo address was correct and _**current**_ is spelled correctly.

I was able to resolve this issue two different ways. The first way is to add a **/** at the end of the address, e.g. https://mirrors.servercentral.com/voidlinux/current/, or add an extra **t** at the end of _**current**_, spelling it **_currentt_**. Both of these actions allows xbps to utilize the mirror without issue.

I did not have this issue with the 10-repository-multilib.conf, 10-repository-multilib-nonfree.conf, or 10-repository-nonfree.conf repos while utilizing the https://mirrors.servercentral.com/voidlinux/current mirror.

I was unable to reproduce this issue with the https://alpha.de.repo.voidlinux.org/current mirror. The issue has persisted after fully updating my system as of 6 Feb 2022.

**Comment by Duncaen** [comment]
Probably missing a trailing newline character, I think that is already fixed in master.

**Comment by 2eb7a27b** [comment]
You are right! I put a return after the line and it solved the issue. Is that normal behavior, or is that change what you are talking about being fixed in master?

**Comment by Duncaen** [comment]
Its a bug and its fixed in master.
