### ISSUE TITLE
Indicate Orphaned (ie. no maintainer) packages in `xbps-query -Rs`

### ISSUE THREAD

**Issue by subnut** [void-linux/xbps#468]
Many packages are orphaned. I don't think they should be removed from the repo, but there should be an indication that a package is orphaned while listing/installing it.

Because many of the orphaned packages contain subtle errors, which may confuse users, because the application _seems_ to be working well enough.

**Comment by Duncaen** [comment]
`xbps-query -RS` already shows the maintainer field.

Maintainer status does not really tell the full story, packages may be orphaned with or without a maintainer set and they may still be maintained by other people.
