### ISSUE TITLE
document package properties (xbps-query -p)?

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/xbps#470]
It would be nice to have the list of possible properties used in `xbps-query -p` documented somewhere other than the shell completion files (some users on IRC were trying to figure out what the list of all properties were). Not quite sure what that would look like and where it would go, but if y'all have any idea for that, I can take a stab at writing it.

**Comment by Duncaen** [comment]
`xbps-query -S` shows all available pairs for a given package, not sure if we should be maintaining a list in `xbps-query.1` or just refer to `-S`. One downside of referring to `-S` is that some keys are optional like `install-script`, `remove-script` and `automatic` so they don't show up for every package.
Maybe it is also necessary to document what some of the keys are there for, like `automatic` when a package is installed automatically as a dependency and not manually by the user.

**Comment by classabbyamp** [comment]
solved by 2f7feb807427bf6923ae7cd4a1b97387211815eb
