### ISSUE TITLE
 xbps-query: --owned-by with --repository pointing to local repository starts to search configured remote repository similar to -R

### ISSUE THREAD

**Issue by Animeshz** [void-linux/xbps#477]

**Comment by Animeshz** [comment]
Or is it default behavior that using `--repository` also adds a `--repository=<thing at /etc/xbps.d/00-repository-main.conf>` implicitly in allowance of remote repository? If yes, is there a way to search from only required repository without addition of that?

**Comment by Duncaen** [comment]
`--repository` is `-R`, `-R` means use repositories, there is no difference between remote and local repositories when working in repository mode.
You can disabled repositories from configuration files with the `-i/--ignore-conf-repos` flag.
