### ISSUE TITLE
xbps-install returns nonzero if package is already installed

### ISSUE THREAD

**Issue by rroohhh** [void-linux/xbps#51]
see title,
at https://github.com/void-linux/xbps/blob/master/bin/xbps-install/main.c#L258 when more than one package is specified, zero is returned when a package is reinstalled, but I am not sure why this is only the case when more than one package is specified, I would expect the same behaviour for only one package.

**Comment by Duncaen** [comment]
https://github.com/voidlinux/xbps/issues/53

**Comment by xtraeme** [comment]
Reinstall should result in an expected result, so that reinstall == install
