### ISSUE TITLE
xbps-install aarch64-repodata not found when installing void linux via chroot

### ISSUE THREAD

**Issue by ckyoog** [void-linux/xbps#527]
I am following the guide https://docs.voidlinux.org/installation/guides/chroot.html to install `void linux` on an **aarch64** machine. I failed to continue when I get to this step,
```
REPO=https://repo-default.voidlinux.org/current
ARCH=aarch64
XBPS_ARCH=$ARCH xbps-install -S -r /mnt -R "$REPO" base-system
```
The error is
```
[*] Updating repository `https://repo-default.voidlinux.org/current/aarch64-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo-default.voidlinux.org/current/aarch64-repodata': Not Found
```

I found a possibly related issue, https://github.com/void-linux/void-infrastructure/issues/1. There is a comment from @the-maldridge saying this,
> For other people looking through, for historical reasons aarch64-repodata lives in a subdirectory under current, same for the musl packages and associated files.

If it is true, what the subdirectory under "current" is for aarch64-repodata? and isn't `xbps-install` supposed to handle the subdirectory-issue automatically?

**Comment by classabbyamp** [comment]
it's /current/aarch64

**Comment by paper42** [comment]
This is documented in https://docs.voidlinux.org/xbps/repositories/index.html#the-main-repository linked from https://docs.voidlinux.org/installation/guides/chroot.html#the-xbps-method

**Comment by ckyoog** [comment]
Thanks! @classabbyamp and @paper42. I did not notice the link ["the appropriate URL"](https://docs.voidlinux.org/xbps/repositories/index.html#the-main-repository) in the ["chroot"](https://docs.voidlinux.org/installation/guides/chroot.html#the-xbps-method) guide, which is my fault.
