### ISSUE TITLE
Searchable long text 

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/xbps#53]
With reference to [this](https://github.com/void-linux/void-packages/issues/6883)

It would be useful to have some searchable longer text for each package. Maybe displayed via a switch for xbps-query for a specific package? 

The longer text could give a better explanation of the software's purpose and/or any limitations on Void; such as features left out and why. An example being aspell compiled out of weechat-aspell and it being necessary hunspell or similar is installed instead. In #6883 it was mentioned that INSTALL.msg serves the latter part of this purpose but even with a decent resolution, the messages can whizz past and there is little chance to read them or even notice they are there. 

It is not a bug but an enhancement request. It is one of the few features in Debian I miss.

**Comment by xtraeme** [comment]
True, years ago there was long_desc but it used too much space and I decided to remove it. I've got new ideas to implement this without performing a performance penalty.

**Comment by xtraeme** [comment]
btw, you can print `INSTALL.msg` or `REMOVE.msg` with `xbps-query` both for local and remote:

```
$ xbps-query -p install-msg -R foo
$ xbps-query -p remove-msg -R foo
```

So I think this issue is unexistent.
