### ISSUE TITLE
[question] xbps-query does not keep track of certain files

### ISSUE THREAD

**Issue by dkwo** [void-linux/xbps#545]
It seems that `xbps-query` does not keep track of files like
```
/usr/lib/firmware/brcm/*
/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
/usr/lib/gtk-3.0/3.0.0/immodules.cache
/usr/lib/python3.11/__phello__/*
/usr/lib/python3.11/__pycache__/*
/usr/share/applications/mimeinfo.cache
/usr/share/fonts/*
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/share/hplip/__pycache__/__init__.cpython-311.opt-1.pyc
/usr/share/icons/Adwaita/icon-theme.cache
/usr/share/icons/hicolor/icon-theme.cache
/usr/share/man/mandoc.db
/usr/share/mime/*
/usr/share/perl5/vendor_perl/XML/SAX/ParserDetails.ini
/usr/share/texmf-config/ls-R
/usr/share/texmf-config/web2c/updmap.cfg
/usr/share/texmf-dist/ls-R
/usr/share/texmf-var/*
```
I discoverd these files using the script at the end of the xbps home page; `xlocate` also does not keep track of them. Both use `xbps-query`, hence my question: is this expected, or should these files be tracked by `xpbs`, as they were installed by it?

**Comment by paper42** [comment]
There is often no single package that provides these files. They are cache files generated at runtime by some program, ran either by you, xbps trigger or an INSTALL script. I don't think xbps can possibly track them without a lot of work - xbps would have to know which packages can possibly use these files and know what generates them.

**Comment by dkwo** [comment]
I see, thanks for the explanation.
