### ISSUE TITLE
No way to override install-date field

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/xbps#55]
The xbps database contains a field called install-date. For reproducible image builds, it would be useful to be able to set that date/time to a constant. There is a similar issue with the package repository something was installed from, but I am not sure how to address that.

**Comment by xtraeme** [comment]
Easy, just modify libxbps to set a fixed date (epoch)

**Comment by xtraeme** [comment]
Been thinking on this right now. xbps-install(1) might have a new option like --reproducible to skip adding this to pkgdb.

What do you think?

**Comment by xtraeme** [comment]
For reproducable builds the `build-date` obj set by xbps-create(1) should be removed.

**Comment by xtraeme** [comment]
Hmm and this obj `build-date` is completely missnamed. It's the date when the pkg was added to the repository index!

I'm going to clean all this up :-)

**Comment by xtraeme** [comment]
I've just implemented this :-)

**Comment by xtraeme** [comment]
```
[juan@leysa xbps]$ LANG=C git status
On branch reproducible-v2
```

**Comment by CameronNemo** [comment]
Hmm package repository is still there, but there are workarounds for that. I noticed that variable sticking out when I built my image using alpha.de.repo.voidlinux.org and michael built his images on the builder itself using an absolute file path. Workaround would be to mirror the repository into the same path michael is using.

**Comment by xtraeme** [comment]
This obj is only added by libxbps, but it's not stored anywhere.

**Comment by xtraeme** [comment]
So that it's stored temporarily on memory and after xbps_end() it's lost and not saved anywhere.

**Comment by xtraeme** [comment]
Oh I see, I was wrong. You are right.

**Comment by xtraeme** [comment]
@CameronNemo https://github.com/void-linux/xbps/commit/d68ff7ebf0d8a4d1a1f1f40ddac84fdbd5df0b27

**Comment by xtraeme** [comment]
This should now be fixed. Please reopen otherwise.
