### ISSUE TITLE
Undefined reference to `archive_*` functions

### ISSUE THREAD

**Issue by abrendtro** [void-linux/xbps#550]
I have [`libarchive`](https://github.com/libarchive/libarchive) installed on my system, along with header files. XBPS fails to link `main.o`, reporting undefined references even though `/usr/local/lib/libarchive.so` exists

**Comment by classabbyamp** [comment]
do you have pkg-config and libarchive's pc file installed?

https://github.com/void-linux/xbps/blob/master/configure#L688-L702

**Comment by abrendtro** [comment]
Yep:

```
$ pkg-config --cflags libarchive
-I/usr/local/include
```

**Comment by classabbyamp** [comment]
can you post a make log after configuring with `--verbose`? or at least the actual errors?

**Comment by abrendtro** [comment]
I'm sorry for the (very) late reply. I haven't used XBPS since then, but the build works on Ubuntu (after removing `-Werror`)
