### ISSUE TITLE
xbps wants to remove manually installed packages with `xbps-remove -o`

### ISSUE THREAD

**Issue by ShinyZero0** [void-linux/xbps#556]
That's a partial list of what it suggests to remove:

```bash
bottom              remove    0.9.1_1           -                      -
cabextract          remove    1.11_1            -                      -
dcraw               remove    9.28.0_1          -                      -
dmenu               remove    5.2_1             -                      -
execline            remove    2.9.2.0_1         -                      -
exiftool            remove    12.62_1           -                      -
fbida-exiftran      remove    2.14_3            -                      -
fbida-fbi           remove    2.14_3            -                      -
fbida-fbpdf         remove    2.14_3            -                      -
gcr                 remove    3.41.1_1          -                      -
lftp                remove    4.9.2_2           -                      -
libchamplain        remove    0.12.20_1         -                      -
libhwloc            remove    2.9.1_1           -                      -
libjpeg-turbo-tools remove    2.1.5.1_1         -                      -
libmagick           remove    7.1.1.8_1         -                      -
libmspack           remove    0.10.1alpha_1     -                      -
libparted           remove    3.5_1             -                      -
libraqm             remove    0.7.0_1           -                      -
libwmf              remove    0.2.8.4_18        -                      -
neovim              remove    0.8.3_1           -                      -
perl-Fuse           remove    0.16_16           -                      -
perl-IPC-Run        remove    20200505.0_2      -                      -
poppler-glib        remove    23.05.0_1         -                      -
python3-Pillow      remove    9.5.0_2           -                      -
skalibs             remove    2.13.1.0_1        -                      -
telegram-desktop    remove    4.8.1_3           -                      -
ttf-opensans        remove    3.001_1           -                      -
xsel                remove    1.2.1_1           -                      -
```

It can be seen that it wants to remove xsel.
I'm sure i installed it manually, but well, i removed googler which had it as dependency so that is somehow justified (no).

Well, neovim is downgraded and repolocked to 0.8.3, maybe i broke it when was locking it.

But how it concluded that TELEGRAM is orphaned?
Or how could it install the bottom automatically?
These obviously couldn't be dependencies.

I tried running `xbps-pkgdb -a` (after i encountered the problem) as it's stated in manpage that it can fix something (it didn't).
I am now adding the manual mode to the packages that i'm sure i installed but that sucks.
That wouldn't be cool if it'd accidentally remove base-system one day.

Only unordinary things i did with xbps were:

- building the xanmod kernel using local void-packages and installing it with `xi`
- building neovim 0.8.3 in the same local void-packages and installing it like 10 times (no luck with 0.9 every time) with `xdowngrade` (or maybe `xi` too) instead of 0.9 from the normal repos.
- repolocking the neovim 0.8.3 with `xbps-pkgdb -m repolock neovim` most of these 10 times

I'm using the latest `xbps-0.59.1_8` from repos. I hoped the problem was caused by some bug earlier (couple of weeks ago) with older version and is now fixed, but seems like xbps still wants to remove my packages, e.g. i removed `googler` recently and it now wants to remove `xsel`

**Comment by Duncaen** [comment]
`xbps-query -S zlib` or `xbps-query -p automatic-install zlib` will show the `automatic-install` state which can be changed with `xbps-pkgdb -m manual pkgname`.

Not sure about your specific cases, but unless you install packages with `xbps-install -A` or change the mode with `xbps-pkgdb` there is not really a way this would randomly change. The xbps updates have nothing to do with any of this and there has been no other bug report with an issue like this.

**Comment by ShinyZero0** [comment]
:sweat_smile: i was updating my packages with `xbps-install -SAu`. :thinking: this installation mode makes sense to keep it clean if i install dependencies to compile something

**Comment by Duncaen** [comment]
Reopening this since this seems like a bug, I think `xbps-install -A` should only mark newly installed packages as automatically installed. When the installation involves an update to a manually installed package, the installation mode should not be changed.
