### ISSUE TITLE
xbps-install, unexpectedly terminates, in docker only on a single machine

### ISSUE THREAD

**Issue by the-eater** [void-linux/xbps#562]
This is a most confusing issue

I have a void linux machine, called gluttony, which runs an i9-9900K. 

and only on this machine, if I run the most recent xbps-install (glibc) variant, in a docker container, it'll unexpectedly terminate. (both musl or xbps-install.static work fine)

If I run xbps-install with `-d`, it at least reports to me that it fails because of the following `[DEBUG] Empty transaction dictionary: Operation not permitted`. but the reasons for that happening are quite unclear to me

I can't reproduce this on any other machine, the machines available to me are an Intel Xeon CPU E3-1241 v3 and an AMD Ryzen 9 5900X

This happens with both the "official" docker image `voidlinux/voidlinux` and my own docker image that I build from a clean install today (this one is shown below).

I welcome any further help in figuring out what exactly is happening

<details>
<summary>Full log</summary>
<pre>
[eater@gluttony swbr]$ docker run -ti d.xr.to/base:glibc bash
[docker:8f8e398cf8f0 /]$ xbps-install -S   
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[docker:8f8e398cf8f0 /]$ xbps-install -y tmux
[docker:8f8e398cf8f0 /]$ xbps-install -d -v -y tmux
[DEBUG] XBPS: 0.59.1 API: 20200221 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://repo-default.voidlinux.org/current' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://repo-default.voidlinux.org/current
[DEBUG] Parsing configuration file: /usr/share/xbps.d/void-virtualpkgs.conf
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps-arch.conf
[DEBUG] /usr/share/xbps.d/xbps-arch.conf: native architecture set to x86_64
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=/var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] keepconf=false
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://repo-default.voidlinux.org/current
[DEBUG] [pkgdb] initialized ok.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] [rpool] `https://repo-default.voidlinux.org/current' registered.
[DEBUG] xbps_repo_get_pkg: found xbps-0.59.1_8
[DEBUG] [rpool] Skipping `xbps-0.59.1_8' (installed: xbps-0.59.1_8) from repository `https://repo-default.voidlinux.org/current'
[DEBUG] xbps_autoupdate: trans_find_pkg xbps: 17
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found tmux-3.3a_2
Found tmux-3.3a_2 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `tmux-3.3a_2' stored (https://repo-default.voidlinux.org/current)
[DEBUG] xbps_transaction_install_pkg: trans_find_pkg tmux: 0
[DEBUG] xbps_transaction_prepare: processing deps
[DEBUG] Finding required dependencies for 'tmux-3.3a_2':
[DEBUG] tmux-3.3a_2: requires dependency 'glibc>=2.32_1': installed `glibc-2.36_1'.
[DEBUG] tmux-3.3a_2: requires dependency 'libevent>=2.1.11_1': not installed.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found libevent-2.1.12_2
[DEBUG] libevent-2.1.12_2: finding dependencies:
[DEBUG]  libevent-2.1.12_2: requires dependency 'glibc>=2.32_1': installed `glibc-2.36_1'.
[DEBUG]  libevent-2.1.12_2: requires dependency 'libssl1.1>=1.1.1f_1': installed `libssl1.1-1.1.1t_1'.
[DEBUG]  libevent-2.1.12_2: requires dependency 'libcrypto1.1>=1.1.1f_1': installed `libcrypto1.1-1.1.1t_1'.
Found libevent-2.1.12_2 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `libevent-2.1.12_2' stored (https://repo-default.voidlinux.org/current)
[DEBUG] tmux-3.3a_2: requires dependency 'libutempter>=1.1.5_1': not installed.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found libutempter-1.2.1_2
[DEBUG] libutempter-1.2.1_2: finding dependencies:
[DEBUG]  libutempter-1.2.1_2: requires dependency 'glibc>=2.32_1': installed `glibc-2.36_1'.
Found libutempter-1.2.1_2 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `libutempter-1.2.1_2' stored (https://repo-default.voidlinux.org/current)
[DEBUG] tmux-3.3a_2: requires dependency 'ncurses-base>=0': installed `ncurses-base-6.4_1'.
[DEBUG] tmux-3.3a_2: requires dependency 'ncurses-libs>=5.8_1': not installed.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found ncurses-libs-6.4_1
[DEBUG] ncurses-libs-6.4_1: finding dependencies:
[DEBUG]  ncurses-libs-6.4_1: requires dependency 'glibc>=2.36_1': installed `glibc-2.36_1'.
Found ncurses-libs-6.4_1 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `ncurses-libs-6.4_1' stored (https://repo-default.voidlinux.org/current)
[DEBUG] xbps_transaction_prepare: checking on hold pkgs
[DEBUG] xbps_transaction_prepare: checking replaces
[DEBUG] xbps_transaction_prepare: checking revdeps
[DEBUG] xbps_transaction_prepare: checking conflicts
[DEBUG] Empty transaction dictionary: Operation not permitted
[DEBUG] xbps_pkgdb_unlock: pkgdb_fd 3
[DEBUG] [pkgdb] released ok.
</pre>
</details>

**Comment by classabbyamp** [comment]
"official" as in from docker hub or ghcr?

**Comment by the-eater** [comment]
docker hub, haven't really been keeping up to date tbh is ghcr the way to go these days?

will be very surprised if it changes anything tho lol

On June 30, 2023 2:13:01 AM GMT+02:00, classabbyamp ***@***.***> wrote:
>"official" as in from docker hub or ghcr? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/xbps/issues/562#issuecomment-1613941943
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by classabbyamp** [comment]
yeah, the docker hub one was deprecated a while back and should probably be removed

**Comment by the-eater** [comment]
As expected, same issue on `ghcr.io/void-linux/void-linux:latest-thin-x86_64`

<details>
<summary>Full log</summary>
<pre>
[eater@gluttony base]$ docker run -ti ghcr.io/void-linux/void-linux:latest-thin-x86_64 sh
# xbps-install -S
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
x86_64-repodata: 1841KB [avg rate: 52GB/s]
# xbps-install -y tmux
# xbps-install -v -y -d tmux
[DEBUG] XBPS: 0.59.1 API: 20200221 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Parsing configuration file: /etc/xbps.d/noextract.conf
[DEBUG] Added noextract pattern: /etc/sv*
[DEBUG] Added noextract pattern: /usr/local*
[DEBUG] Added noextract pattern: /usr/share/man*
[DEBUG] Added noextract pattern: /usr/lib/dracut*
[DEBUG] Added noextract pattern: /etc/skel*
[DEBUG] Added noextract pattern: /usr/lib/modprobe.d*
[DEBUG] Added noextract pattern: /usr/lib/sysctl.d*
[DEBUG] Added noextract pattern: /usr/lib/udev*
[DEBUG] Added noextract pattern: /usr/share/bash-completion*
[DEBUG] Added noextract pattern: /usr/share/info*
[DEBUG] Added noextract pattern: /usr/share/locale*
[DEBUG] Added noextract pattern: /usr/lib/gconv*
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://repo-default.voidlinux.org/current' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://repo-default.voidlinux.org/current
[DEBUG] Parsing configuration file: /usr/share/xbps.d/void-virtualpkgs.conf
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps-arch.conf
[DEBUG] /usr/share/xbps.d/xbps-arch.conf: native architecture set to x86_64
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=/var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] keepconf=false
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://repo-default.voidlinux.org/current
[DEBUG] [pkgdb] added vpkg awk-0_1 for gawk
[DEBUG] [pkgdb] initialized ok.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] [rpool] `https://repo-default.voidlinux.org/current' registered.
[DEBUG] xbps_repo_get_pkg: found xbps-0.59.1_8
[DEBUG] [rpool] Skipping `xbps-0.59.1_8' (installed: xbps-0.59.1_8) from repository `https://repo-default.voidlinux.org/current'
[DEBUG] xbps_autoupdate: trans_find_pkg xbps: 17
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found tmux-3.3a_2
Found tmux-3.3a_2 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `tmux-3.3a_2' stored (https://repo-default.voidlinux.org/current)
[DEBUG] xbps_transaction_install_pkg: trans_find_pkg tmux: 0
[DEBUG] xbps_transaction_prepare: processing deps
[DEBUG] Finding required dependencies for 'tmux-3.3a_2':
[DEBUG] tmux-3.3a_2: requires dependency 'glibc>=2.32_1': installed `glibc-2.36_1'.
[DEBUG] tmux-3.3a_2: requires dependency 'libevent>=2.1.11_1': not installed.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found libevent-2.1.12_2
[DEBUG] libevent-2.1.12_2: finding dependencies:
[DEBUG]  libevent-2.1.12_2: requires dependency 'glibc>=2.32_1': installed `glibc-2.36_1'.
[DEBUG]  libevent-2.1.12_2: requires dependency 'libssl1.1>=1.1.1f_1': installed `libssl1.1-1.1.1s_1'.
[DEBUG]  libevent-2.1.12_2: requires dependency 'libcrypto1.1>=1.1.1f_1': installed `libcrypto1.1-1.1.1s_1'.
Found libevent-2.1.12_2 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `libevent-2.1.12_2' stored (https://repo-default.voidlinux.org/current)
[DEBUG] tmux-3.3a_2: requires dependency 'libutempter>=1.1.5_1': not installed.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found libutempter-1.2.1_2
[DEBUG] libutempter-1.2.1_2: finding dependencies:
[DEBUG]  libutempter-1.2.1_2: requires dependency 'glibc>=2.32_1': installed `glibc-2.36_1'.
Found libutempter-1.2.1_2 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `libutempter-1.2.1_2' stored (https://repo-default.voidlinux.org/current)
[DEBUG] tmux-3.3a_2: requires dependency 'ncurses-base>=0': not installed.
[DEBUG] [rpool] checking `https://repo-default.voidlinux.org/current' at index 0
[DEBUG] xbps_repo_get_pkg: found ncurses-base-6.4_1
Found ncurses-base-6.4_1 in repository https://repo-default.voidlinux.org/current
[DEBUG] [trans] `ncurses-base-6.4_1' stored (https://repo-default.voidlinux.org/current)
[DEBUG] tmux-3.3a_2: requires dependency 'ncurses-libs>=5.8_1': installed `ncurses-libs-6.3_3'.
[DEBUG] xbps_transaction_prepare: checking on hold pkgs
[DEBUG] xbps_transaction_prepare: checking replaces
[DEBUG] xbps_transaction_prepare: checking revdeps
[DEBUG] xbps_transaction_prepare: checking conflicts
[DEBUG] Empty transaction dictionary: Operation not permitted
[DEBUG] xbps_pkgdb_unlock: pkgdb_fd 3
[DEBUG] [pkgdb] released ok.
# 

</pre>
</details>

**Comment by the-eater** [comment]
oh after fucking around I found something, yay user error, but extremely fucking obscure

```
# dig gamer.com
thread.c:82: fatal error: pthread_create() failed: Operation not permitted
Aborted
```

**Comment by the-eater** [comment]
eater just had to restart the docker service and then it wouldn't have made an ass out of itself

**Comment by leahneukirchen** [comment]
This sounds like insufficient error reporting in xbps, however. The only use of `pthread_create` is in `xbps_array_foreach_cb_multi`... the `xbps_dbg_printf` in `bin/xbps-install/transaction.c` should probably be fatal?
