### ISSUE TITLE
xlocate -S bougus request

### ISSUE THREAD

**Issue by hholst80** [void-linux/xbps#563]
![image](https://github.com/void-linux/xbps/assets/6200749/35baddaa-c39c-4e48-9d21-417aa271f8cf)

**Comment by classabbyamp** [comment]
this should be reported to [xtools](https://github.com/leahneukirchen/xtools)

**Comment by Chocimier** [comment]
it correctly returns no results as you used too specific term

**Comment by hholst80** [comment]
The problem is obviously the error message - the database is not outdated. Please move this issue over to xtools so it can be fixed. Thanks!

**Comment by classabbyamp** [comment]
we can't move it. xtools is not a void repo.

**Comment by hholst80** [comment]
Ah, sorry. Got it. I'll make a new issue over there.
