### ISSUE TITLE
Transient resolver failure in base Install, when setting XBPS_ARCH (IP adress not in resolv.conf))

### ISSUE THREAD

**Issue by ygol55** [void-linux/xbps#564]
After following all steps at the page 'Installation via chroot' and imaging the Void x86_64 .iso file into a USB, I'm getting the error: 'Transient resolver failure'. That's after I've tried to enter the IP address to the file resolv.conf of the default install, which wasn't there in default when installing.

**Comment by Duncaen** [comment]
Yes you need name servers, either manually configured or configured by your network manager through dhcp or some other mechanism.
