### ISSUE TITLE
Inconsistant sigsegv on void-musl wsl xbps-install -Su

### ISSUE THREAD

**Issue by Matthieu-Sauer** [void-linux/xbps#567]
I sometimes encounter a segmentation fault when upgrading my wsl void-musl system.

_Command used_:
```
xbps-install -Su
```
_Base system_:
```
windows 10 pro
WSL 2 void-linux with musl libc (no glibc compatibility installed)
```

Re-running the command fixes the issue, therefore I cannot reproduce it to pinpoint the error source. (and I did not take a screenshot of the error, dumb as I am). it is not really annoying as it is fixed in a few seconds.

Is there a way to enable loggings of the xbps suite so I can know exactly where the issue comes from on wsl system (I don't think there is runit services on wsl)? (which package causes it).
It happens about once or twice a month, and it seems to be related to python packages, unsure therefore if this is the correct repository to report this?

If the issue is wsl-related, I will simply ignore it (and you can close the issue) as I know it is not the primary target of void and xbps.

**Comment by Duncaen** [comment]
xbps logs some information to syslog, but its most likely not verbose enough to make any guess to why its segfaulting.
The best way to debug segfaults is to enable coredumps or use gdb to get bracktraces of the crashes.

**Comment by Matthieu-Sauer** [comment]
I did not encounter the crash again, either gdb is correcting the crash (and that is why I do not witness it anymore) or it has been patched (maybe in the package that was causing it). I will close this issue, and reopen it if I ever have the problem again. (while disabling gdb).

**Comment by Matthieu-Sauer** [comment]
I actually just encountered the crash. here it is (without gdb sadly).

```
sudo xbps-install -Su
Password:
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/x86_64-musl-repodata' ...
x86_64-musl-repodata: 1831KB [avg rate: 820KB/s]
[*] Updating repository `https://repo-default.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...

Name            Action    Version           New version            Download size
btrfs-progs     update    6.3.3_1           6.5.1_1                977KB
kbd             update    2.6.2_1           2.6.3_1                1230KB
perl            update    5.36.1_1          5.38.0_1               14MB
perl-Net-SSLeay update    1.92_3            1.92_4                 261KB
vim             update    9.0.1903_1        9.0.1903_2             1856KB
vim-common      update    9.0.1903_1        9.0.1903_2             8479KB
xxd             update    9.0.1903_1        9.0.1903_2             15KB

Size to download:               27MB
Size required on disk:         121MB
Space available on disk:      1002GB

Do you want to continue? [Y/n] y

[*] Downloading packages
btrfs-progs-6.5.1_1.x86_64-musl.xbps.sig2: 512B [avg rate: 13MB/s]
[1]    307 segmentation fault  sudo xbps-install -Su%] 74MB/s ETA: 00m00s
```

**Comment by Matthieu-Sauer** [comment]
if I rerun the command, it runs fine.

**Comment by Matthieu-Sauer** [comment]
did not encounter it since, closing
