### ISSUE TITLE
ignorepkg=sudo not working

### ISSUE THREAD

**Issue by levdopa** [void-linux/xbps#570]
I have ignorepkg=sudo in /usr/share/xbps.d/xbps.conf and it's not working because 
in transaction breaks installed pkg 'base-system-0.114_1'

I've done this like a million times before I don't know why it's not working now
there are no spelling mistakes, its in the right file, and other ignorepkg commands in the file are working. Its only the ones that break base-system that dont work.

**Comment by Duncaen** [comment]
1. don't edit files in `/usr` they are being overwritten on updates, you should drop a file in `/etc/xbps.d`.

Show the debug log if you are sure that the change was not overwritten by 1.

**Comment by levdopa** [comment]
I changed it to /etc/xbps.d/xbps.conf, still same issue.
not sure what you mean by debug log but this is the command and error
xbps-remove sudo
sudo-1.9.14p3_1 in transaction breaks installed pkg 'base-system-0.114_1'
Transaction aborted due to unresolved dependencies.

And I just added ignorepkg=less in the same file I did ignorepkg=sudo and
less is able to be removed now. So some packages are behaving normally and some are impossible to remove.

**Comment by Duncaen** [comment]
`xbps-remove --debug --verbose sudo`.

**Comment by levdopa** [comment]
[DEBUG] XBPS: 0.59.1 API: 20200221 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Parsing configuration file: /etc/xbps.d/xbps.conf
[DEBUG] Added ignored package: sudo 
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://repo-default.voidlinux.org/current/musl' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://repo-default.voidlinux.org/current/musl
[DEBUG] Parsing configuration file: /usr/share/xbps.d/void-virtualpkgs.conf
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps-arch.conf
[DEBUG] /usr/share/xbps.d/xbps-arch.conf: native architecture set to x86_64-musl
[DEBUG] rootdir=/
[DEBUG] metadir=/var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] keepconf=false
[DEBUG] Architecture: x86_64-musl
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://repo-default.voidlinux.org/current/musl
[DEBUG] [pkgdb] added vpkg libudev-243_1 for eudev-libudev
[DEBUG] [pkgdb] added vpkg awk-0_1 for gawk
[DEBUG] [pkgdb] added vpkg man-0_1 for mdocml
[DEBUG] [pkgdb] added vpkg eject-2.38.1_1 for util-linux
[DEBUG] [pkgdb] added vpkg rfkill-2.38.1_1 for util-linux
[DEBUG] [pkgdb] initialized ok.
[DEBUG] [trans] `sudo-1.9.14p3_1' stored (https://repo-default.voidlinux.org/current/musl)
[DEBUG] xbps_transaction_prepare: processing deps
[DEBUG] xbps_transaction_prepare: checking on hold pkgs
[DEBUG] xbps_transaction_prepare: checking replaces
[DEBUG] xbps_transaction_prepare: checking revdeps
[DEBUG] vpkg_user_conf: vpkg_conf awk-0_1 pkg gawk vpkgname awk
sudo-1.9.14p3_1 in transaction breaks installed pkg `base-system-0.114_1'
Transaction aborted due to unresolved dependencies.
[DEBUG] xbps_pkgdb_unlock: pkgdb_fd 3
[DEBUG] [pkgdb] released ok.

**Comment by Duncaen** [comment]
Your log has a trailing space in the relevant log line `[DEBUG] Added ignored package: sudo `, is this also in the file?

**Comment by levdopa** [comment]
yeah I went into the file and deleted the space it works now thanks
