### ISSUE TITLE
`_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE`

### ISSUE THREAD

**Issue by pbsds** [void-linux/xbps#576]
On glibc 3.38.23 i get the warning-turned-error:

```
_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE
```

The [fix seems to](https://stackoverflow.com/a/29201732/5303896) additionally define `_DEFAULT_SOURCE` whenever `_BSD_SOURCE` is defined.

**Comment by classabbyamp** [comment]
fixed by #581
