### ISSUE TITLE
ERROR: [reposync] failed to fetch file

### ISSUE THREAD

**Issue by don-dolarson** [void-linux/xbps#578]
Trying to set up FDE as per docs [here](https://docs.voidlinux.org/installation/guides/fde.html) but I'm stuck.

> Before we enter the chroot to finish up configuration, we do the actual install. Do not forget to use the [appropriate repository URL](https://docs.voidlinux.org/xbps/repositories/index.html#the-main-repository) for the type of system you wish to install.
> 
> # xbps-install -Sy -R https://repo-default.voidlinux.org/current -r /mnt base-system lvm2 cryptsetup grub

However, this is what I get
![Void_Linux](https://github.com/void-linux/xbps/assets/49354563/75e3af1c-5cc3-4e2f-88c8-8f1b2408157d)

Tried to change the address to the one with **_/x86_64/musl/_** in it, the same address which showing up when syncing repos when running xbps-install -S (which works) but the same problem appear.

**Comment by classabbyamp** [comment]
the correct address for musl is `.../current/musl`, as specified in the link in the documentation you quoted:

> Do not forget to use the [appropriate repository URL](https://docs.voidlinux.org/xbps/repositories/index.html#the-main-repository) for the type of system you wish to install.

If you meant to install glibc, you should set `XBPS_ARCH=x86_64` in the environment if you're installing from a musl environment.
