### ISSUE TITLE
HTTP proxy issues on WSL with CNTLM

### ISSUE THREAD

**Issue by isiandrasi** [void-linux/xbps#72]
Hi!

I run void glibc on WSL using [VoidWSL](https://github.com/am11/VoidWSL). My environment is probably uncommon, but I don't think that's the cause (see curl results).

I'm behind an NTLM proxy, and I use `cntlm` for authentication. This is the relevant `cntlm` config:
~~~
Listen      5555
SOCKS5Proxy 5000
~~~

I expect xbps to work through the proxy, but it fails:
~~~
# sudo http_proxy=http://127.0.0.1:5555 xbps-install -S
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Success
#
~~~

Interestingly, when I use the SOCKS proxy, it works:
~~~
# sudo SOCKS_PROXY=socks5://127.0.0.1:5000 xbps-install -S
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
#
~~~

I also tested the proxy using curl:
~~~
# curl -ILx 127.0.0.1:5555 https://alpha.de.repo.voidlinux.org/current/x86_64-repodata
HTTP/1.1 200 Connection established
Via: 1.1 MYPROXY1, 1.1 MYPROXY2
Connection: Keep-Alive
Proxy-Connection: Keep-Alive

HTTP/2 200
server: nginx
date: Wed, 20 Mar 2019 12:37:24 GMT
content-type: application/octet-stream
content-length: 1832385
last-modified: Wed, 20 Mar 2019 10:35:19 GMT
etag: "5c921767-1bf5c1"
accept-ranges: bytes
#
~~~

Without specifying the proxy for curl, it times out:
~~~
# curl -IL https://alpha.de.repo.voidlinux.org/current/x86_64-repodata
curl: (7) Failed to connect to alpha.de.repo.voidlinux.org port 443: Connection refused
#
~~~

I think if curl works thorugh the proxy, xbps should also work.

**Comment by Duncaen** [comment]
I think this might also be fixed by https://github.com/void-linux/xbps/commit/07ec982b078f8672c8cdbb42bf2e861c969ab40b.

I added the patch to the `xbps-0.53_9` (https://github.com/void-linux/void-packages/commit/524e6999e3945dd0831797ea2f6ac2065e2549b9), which should be available as updated in a bit.

**Comment by isiandrasi** [comment]
With `xbps-0.53_9` it now works as expected. Thanks for the fix!
