### ISSUE TITLE
xbps not work with authenticated proxy 

### ISSUE THREAD

**Issue by noloop** [void-linux/xbps#75]
How do I use xbps with an authenticated proxy? what configuration do I have to do? I'm looking for an example because I've tried configuring the environment variable and nothing, I'm almost buying a service and creating a VPN server on it to be able to connect without dealing with the proxy, but I'd really like to learn how to connect to a proxy network on voidlinux xbps.

**uname -a:** `Linux noloop 4.19.30_1 #1 SMP PREEMPT Wed Mar 20 09:17:21 UTC 2019 x86_64 GNU/Linux`
**xbps-install -V:** `XBPS: 0.53 API: 20180730 GIT: UNSET`

What I tried and did not succeed so far:

```
export HTTP_PROXY=http://user1:123@162.16.78.1:3128
export HTTPS_PROXY=http://user1:123@162.16.78.1:3128
export FTP_PROXY=http://user1:123@162.16.78.1:3128
```

I've already tried it:

```
 export HTTP_PROXY=http://user1:123@162.16.78.1:3128/
 export HTTPS_PROXY=http://user1:123@162.16.78.1:3128/
 export FTP_PROXY=http://user1:123@162.16.78.1:3128/
```

or:

```
export http_proxy="http://user1:123@162.16.78.1:3128"
export https_proxy="http://user1:123@162.16.78.1:3128"
export ftp_proxy="http://user1:123@162.16.78.1:3128"
```

or

```
export http_proxy="http://user1:123@162.16.78.1:3128/"
export https_proxy="http://user1:123@162.16.78.1:3128/"
export ftp_proxy="http://user1:123@162.16.78.1:3128/"
```

If I run the command below after configuring the environment variables, I get the following error:

```
noloop@noloop:~$ sudo xbps-install -v -S 
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Connection timed out
```

_**Note: And yes that username and password, as well as the address and ports are correct because when setting the /etc/apt/apt.conf.d/00proxy file with this data in a debian like, it works as expected. And also with other programs, how it works, however with xbps not.**_

**Comment by Duncaen** [comment]
https://github.com/void-linux/xbps/blob/master/lib/fetch/http.c#L706

It should work with user/password in the url or using the `HTTP_PROXY_AUTH` environment variable.

Otherwise a log from wireshark or something similar would be interesting to debug.

**Comment by noloop** [comment]
Okay, tonight I'll try and bring the return.

**Comment by noloop** [comment]
It did not work, I tried with:

```
export http_proxy="http://162.16.78.1:3128"
export ftp_proxy="http://162.16.78.1:3128"
export HTTP_PROXY_AUTH="basic:*:user1:123"
```

And it still does not work for xbps.

**Comment by skrueger8** [comment]
Same problem here.

wget works fine:

```
[root@void ~]# env | grep proxy
https_proxy=http://10.0.2.2:3123
http_proxy=http://10.0.2.2:3128

[root@void ~]# wget https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata
--2019-04-08 11:51:29--  https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata
Connecting to 10.0.2.2:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1780669 (1.7M) [application/octet-stream]
Saving to: ‘x86_64-musl-repodata’

x86_64-musl-repodata           100%[=================================================>]   1.70M  7.34MB/s    in 0.2s

2019-04-08 11:51:29 (7.34 MB/s) - ‘x86_64-musl-repodata’ saved [1780669/1780669]
```

xbps-install does not:

```
[root@void ~]# xbps-install -Suv
[*] Updating `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata': Invalid argument
```

tcpdump -> https://dpaste.de/kZCe#

**Comment by Duncaen** [comment]
One bug was fixed in https://github.com/void-linux/xbps/commit/07ec982b078f8672c8cdbb42bf2e861c969ab40b, but this is not related to authentication (I don't think there is an issue with authentication).

```
13:40:19          duncaen | tested with squid and tinyproxy
13:40:47          duncaen | squid already worked, it doesnt send additional headers after 200 Connection Established
13:41:15          duncaen | tiny proxy sends: Proxy-agent: tinyproxy/1.10.0\r\n\r\n
13:41:54          duncaen | before the patch it just discarded one line and then later sees an empty line before the proxied response and fails
```

I added the patch to the `xbps-0.53_9` (https://github.com/void-linux/void-packages/commit/524e6999e3945dd0831797ea2f6ac2065e2549b9), which should be available as updated in a bit.

**Comment by skrueger8** [comment]
Thanks! Works as intended with xbps-0.53_9!

**Comment by noloop** [comment]
@Duncaen To update to this new patch what do I need to do? to update the void with "sudo xbps-install-su"? I do not know how to update xbps, I never did. Recompile it with the new patch?

**Comment by Duncaen** [comment]
And yes `xbps-install -Su` will update xbps itself if the package is available. 
The `x86_64` buildserver is currently busy building other things including qt5 which might take a while before the xbps update is available.

**Comment by skrueger8** [comment]
@noloop try this:

XXX you might need other updates, depending on how old your packages are, just rinse and repeat for every out-of-date packge...

```
mkdir repo
cd repo
wget https://alpha.de.repo.voidlinux.org/current/musl/libxbps-0.53_9.x86_64-musl.xbps
wget https://alpha.de.repo.voidlinux.org/current/musl/libxbps-0.53_9.x86_64-musl.xbps.sig
wget https://alpha.de.repo.voidlinux.org/current/musl/xbps-0.53_9.x86_64-musl.xbps
wget https://alpha.de.repo.voidlinux.org/current/musl/xbps-0.53_9.x86_64-musl.xbps.sig
wget https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata
echo "repository=$PWD/repo" > /etc/xbps.d/my-local-repo.conf
xbps-install -R /tmp/repo -Su xbps-0.53_9
[*] Updating `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata': Invalid argument

Name    Action    Version           New version            Download size
libxbps update    0.53_8            0.53_9                 -
xbps    update    0.53_8            0.53_9                 -

Size required on disk:          44KB
Space available on disk:      5244MB

Do you want to continue? [Y/n] y

[*] Downloading binary packages

[*] Verifying package integrity
libxbps-0.53_9: verifying SHA256 hash...
xbps-0.53_9: verifying SHA256 hash...

[*] Running transaction tasks
libxbps-0.53_8: updating to 0.53_9 ...
libxbps-0.53_9: unpacking ...
xbps-0.53_8: updating to 0.53_9 ...
xbps-0.53_9: unpacking ...

[*] Configuring unpacked packages
libxbps-0.53_9: configuring ...
libxbps-0.53_9: updated successfully.
xbps-0.53_9: configuring ...
xbps-0.53_9: updated successfully.

0 downloaded, 0 installed, 2 updated, 0 configured, 0 removed.

rm /etc/xbps.d/my-local-repo.conf
```

**Comment by Duncaen** [comment]
Be aware that this example uses `x86_64-musl`, on a glibc system the url and filenames need to be adjusted.
And you need to wait until the `x86_64` build server is finished (https://build.voidlinux.org/waterfall).

**Comment by noloop** [comment]
I'll wait until I get out the update of it to give a simple command "sudo xbps-install -Su", no hurry XD

**Comment by noloop** [comment]
Today I saw that the **xbps-0.53_9** update came out, so I updated and tried to connect with the authenticated proxy of the institution where I study. I have tried in all the ways that I have shown up, and even then it does not work.

**Comment by Duncaen** [comment]
In this case I need wireshark/tcpdump logs. Can't reproduce it with simple authentications.

**Comment by noloop** [comment]
Are you able to connect with an authenticated proxy?

**Comment by noloop** [comment]
I will have to bring the result tomorrow night, since here I can not install tcpdump, I install it today in my house, and tomorrow I bring the result here.

**Comment by noloop** [comment]
Sorry for the delay, I just came here to test now, here is the file generated by `sudo tcpdump -i <interface> -w tcpdump.log` while trying `sudo xbps-install -S` with the various environments configured as shown below:

```
ftp_proxy=http://172.16.48.1:3128
http_proxy=http://172.16.48.1:3128
HTTP_PROXY_AUTH=basic:*:<user>:<pass>
```

[tcpdump.log](https://github.com/void-linux/xbps/files/3087103/tcpdump.log)

**Comment by elpres** [comment]
I'm seeing the same issue behind a proxy with a VirtualBox installation. Our proxy doesn't use authentication though, so the problem can probably narrowed down to "proxy support" in general rather than "authenticated proxy". In the attached Wireshark log it looks like some communication including a TLS handshake is happening.

My installation, which I made using the ISO "void-live-x86_64-musl-20181111.iso" doesn't contain neither `wget` nor `curl`, so until using Wireshark I couldn't even find out whether the VM was able to communicate with the outside network or not. Is there any other programm included in the default installation that could be used to download a file from the web as a connectivity test?

[xbps-install.zip](https://github.com/void-linux/xbps/files/3138277/xbps-install.zip)

**Comment by Duncaen** [comment]
Did you use the latest xbps release with the patch or the version that is currently on the ISO?

**Comment by xtraeme** [comment]
With current master, you can set `--enable-rpath` to test it easily as your user:

```
$ ./configure --enable-debug --enable-rpath --prefix=/usr
$ make && make DESTDIR=$HOME/xbps-git install
$ export PATH="$HOME/xbps-git/usr/bin:$PATH"
$ which xbps-query
...
```

**Comment by xtraeme** [comment]
To test it you can simply run `xbps-uhelper fetch <url>`

**Comment by elpres** [comment]
> Did you use the latest xbps release with the patch or the version that is currently on the ISO?

I used the version that was on the ISO because updating xbps (or anything else) failed with the "Invalid argument" error. As mentioned above, the ISO I used was the plain (no desktop environment) musl x84_64 version dated 20181111, which is still the current one at the moment.

> To test it you can simply run `xbps-uhelper fetch <url>`

Thanks, downloading a random web page with that command worked as expected, the output shows a connection with the proxy and the downloaded result is correct.

**Comment by elpres** [comment]
Ok, the glibc version also fails to run `xbps-install -S`, but with a different error:

```
$ sudo xbps-install -S
[*] Updating `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Success
```

So at least something seems to have gone more successfully...

**Comment by xtraeme** [comment]
use `-d` to see what's going on

**Comment by elpres** [comment]
Here's the log from the musl version:

```
[DEBUG] XBPS: 0.53 API: 20180730 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current/musl' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://alpha.de.repo.voidlinux.org/current/musl
[DEBUG] Parsing configuration file: /usr/share/xbps.d/musl-arch.conf
[DEBUG] /usr/share/xbps.d/musl-arch.conf: native architecture set to x86_64-musl
[DEBUG] Parsing configuration file: /usr/share/xbps.d/void-virtualpkgs.conf
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg awk for gawk
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg cron-daemon for dcron
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg editor for nvi
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg man for openbsd-man
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg ntp-daemon for openntpd
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg openssl for libressl-openssl
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg shell for dash
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg smtp-server for opensmtpd
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: x86_64-musl
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://alpha.de.repo.voidlinux.org/current/musl
[DEBUG] st.st_size: 0
[DEBUG] st.st_atime: 01 Jan 1970 00:00
[DEBUG] st.st_mtime: 01 Jan 1970 00:00
[DEBUG] url_stat.size: -1
[DEBUG] url_stat.atime: 01 Jan 1970 00:00
[DEBUG] url_stat.mtime: 01 Jan 1970 00:00
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata': Invalid argument
[DEBUG] [rpool] `https://alpha.de.repo.voidlinux.org/current/musl' failed to fetch repository data: (null)
[DEBUG] [repo] `//var/db/xbps/https___alpha_de_repo_voidlinux_org_current_musl/x86_64-musl-repodata' open repodata No such file or directory
```

**Comment by xtraeme** [comment]
You aren't using the xbps git version...

**Comment by elpres** [comment]
That is correct, I'm using the version that is on the current ISO. And given that the system comes with no `git` or `make`, I don't see how one could easily obtain the git version. Is there a binary available anywhere that I could at least `scp` into the VM?

**Comment by misirca** [comment]
This might be a Sudo issue.

Sudo commands don't automatically inherit environment variables.

You have to specifically tell sudo to do this.

Add the following line in your visudo config:

Defaults env_keep += "http_proxy https_proxy ftp_proxy"

**Comment by noloop** [comment]
@misirca That's right, sudo was not using the various environments, now is working.

**Comment by elpres** [comment]
Adding the proxy related variables to the visudo defaults doesn't change anything in my case. I set the proxy variables in /etc/environment, which should ensure there existence even in the environment set up by sudo. And as the packet capture shows, the proxy settings were honored, but the sync still aborted with the "Invalid argument" error.

**Comment by Anachron** [comment]
Please make sure the proxy settings are really in the ENV when using sudo. „sudo env | grep proxy“ or similar.

**Comment by elpres** [comment]
It's not a sudo issue:
```
$ sudo env | grep -i proxy
HTTP_PROXY=http://192.168.2.2:3128
https_proxy=http://192.168.2.2:3128
http_proxy=http://192.168.2.2:3128
HTTP_PROXYS=http://192.168.2.2:3128
```
As I already mentioned earlier, I captured the traffic with Wireshark and can see a successful TLS handshake happening, so there is definitely communication happening between `xbps-install` and the remote server. The error occurs after that.

If someone can explain to me how to smuggle `strace` or something similar into the VM, I'll give it a try. I can't download the package with `wget`/`curl` since they don't come with the ISO and can't be installed by `xbps-install`, but what is possible is copying the package using `scp` which is on the ISO. Can someone give me the correct URL for this arch (x64 musl or glibc, I've both as VMs)?

**Comment by xtraeme** [comment]
Are you using xbps from git master? please try `xbps-uhelper -V`

**Comment by xtraeme** [comment]
Easy way for testing:

```
$ git clone https://github.com/void-linux/xbps
$ cd xbps
$ ./configure --enable-rpath --enable-debug --prefix=/usr --sysconfdir=/etc
$ make && make DESTDIR=~/xbps-git install clean
$ export PATH="$HOME/xbps-git/usr/bin:$PATH"
$ xbps-query -V
```

**Comment by elpres** [comment]
```
`$ xbps-uhelper -V
XBPS: 0.53 API: 20180730 GIT: UNSET
```
We already talked about this before: I'm using the version that's on the latest ISO, and can't install anything else because of the proxy problem that this thread is about. `git` and `make` don't come with the ISO, so they are unavailable to me to do what you suggested in the second post.

**Comment by xtraeme** [comment]
I see, so you need a static binary somewhere for testing.

**Comment by misirca** [comment]
After some tests, I second Elpres on this issue, this is not _only_ a sudo-related issue.

There is something wrong between xbps-install and proxies.
Sometimes xbps-install totally ignores proxy settings.

(Note: using sudo on every command below _on purpose_)

Environment variables are set:
```
$ sudo env | grep proxy
http_proxy=127.0.0.1:3128
https_proxy=127.0.0.1:3128
```

CNTLM proxy is running:
```
$ sudo wget https://alpha.de.repo.voidlinux.org/current/x86_64-repodata
 
--2019-07-08 15:04:22--  https://alpha.de.repo.voidlinux.org/current/x86_64-repodata
Connexion à 127.0.0.1:3128… connecté.
requête Proxy transmise, en attente de la réponse… 200 OK
Taille : 1898638 (1,8M) [application/octet-stream]
Sauvegarde en : « x86_64-repodata.7 »

x86_64-repodata.7   100%[===================>]   1,81M  1,34MB/s    ds 1,4s    

2019-07-08 15:04:24 (1,34 MB/s) — « x86_64-repodata.7 » sauvegardé [1898638/1898638]
```

The following commands seem to bypass proxy totally 
(i.e. no connection attempt is even detected by CNTLM)

```
$ sudo xbps-uhelper fetch https://alpha.de.repo.voidlinux.org/current/x86_64-repodata
looking up alpha.de.repo.voidlinux.org
connecting to alpha.de.repo.voidlinux.org:443
connecting to 95.216.76.97
attempted to connect to all addresses, waiting...
https://alpha.de.repo.voidlinux.org/current/x86_64-repodata: Connection refused
```

```
$ sudo xbps-install -S -d
[DEBUG] XBPS: 0.56 API: 20190621 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://alpha.de.repo.voidlinux.org/current
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://alpha.de.repo.voidlinux.org/current
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[DEBUG] st.st_size: 1898638
[DEBUG] st.st_atime: 08 Jul 2019 12:43
[DEBUG] st.st_mtime: 08 Jul 2019 09:17
[DEBUG] url_stat.size: -1
[DEBUG] url_stat.atime: 01 Jan 1970 00:00
[DEBUG] url_stat.mtime: 01 Jan 1970 00:00
ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Connection refused
[DEBUG] [rpool] `https://alpha.de.repo.voidlinux.org/current' failed to fetch repository data: Connection refused
[DEBUG] [rpool] checking `https://alpha.de.repo.voidlinux.org/current' at index 0
[DEBUG] [rpool] `https://alpha.de.repo.voidlinux.org/current' registered.
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current' public key already stored.
```

Same command using 4G tethering (i.e. direct connection, no proxy)

```
$ sudo xbps-install -S -d

[DEBUG] XBPS: 0.56 API: 20190621 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://alpha.de.repo.voidlinux.org/current
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://alpha.de.repo.voidlinux.org/current
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[DEBUG] st.st_size: 1898638
[DEBUG] st.st_atime: 08 Jul 2019 12:43
[DEBUG] st.st_mtime: 08 Jul 2019 09:17
[DEBUG] url_stat.size: -1
[DEBUG] url_stat.atime: 08 Jul 2019 09:17
[DEBUG] url_stat.mtime: 08 Jul 2019 09:17
[DEBUG] [rpool] checking `https://alpha.de.repo.voidlinux.org/current' at index 0
[DEBUG] [rpool] `https://alpha.de.repo.voidlinux.org/current' registered.
[DEBUG] [repo] `https://alpha.de.repo.voidlinux.org/current' public key already stored.
```

Note the difference, _url_stat.atime_ and _url_stat.mtime_ seem valid here, so it might be a certificate check issue.

Shall I reopen another issue report about this?

**Comment by Duncaen** [comment]
Open a new issue and provide network and strace logs if possible.
