### ISSUE TITLE
Kernel Panic after updating void linux

### ISSUE THREAD

**Issue by noloop** [void-linux/xbps#94]
Kernel Panic after updating void linux with `sudo xbps install -Su`.

Update Linux **4.19.15_1** -> **4.19.42_1**

[Img kernel panic screen](https://i.imgur.com/vzXAUnu.jpg)

I can still access the system normally under **Linux 4.19.15_1**

>UP:

I've updated void linux again, and now it has upgraded to **linuz-4.19.44_1** and kernel panic still occurs.

in x86_64.

**Comment by Anachron** [comment]
Is it on aarch64? Because I had the same. But the kernel does not always panic on boot. It‘s quite strange because I believe it has to do with usb devices or lan connection connected. (didn‘t dig deeper because all is well after reinstall).

**Comment by noloop** [comment]
x86_64.

**Comment by Duncaen** [comment]
This is the package manager repository, issues with packages should go into https://github.com/void-linux/void-packages.
